(() => {
  "use strict";

  const officialAuthority = provider =>
    `First-party learning resource published on ${provider}'s official website or course platform.`;
  const youtubeAccess =
    "Public YouTube page; regional availability, login requirements, and subtitle availability may change.";
  const bilibiliAccess =
    "Public Bilibili page; availability may change because of takedowns, regional restrictions, login requirements, or platform anti-abuse controls.";

  const rawResources = [
    {
      platform: "Official resources",
      titleZh: "OpenAI Academy",
      titleEn: "OpenAI Academy",
      provider: "OpenAI",
      language: "English",
      level: "Beginner to Intermediate",
      format: "Online learning hub",
      topics: ["AI literacy", "prompting", "data analysis", "workflow automation", "responsible use"],
      url: "https://academy.openai.com/",
      accessed: "2026-08-22",
      accessNote: "Free public learning hub; regional access may vary",
      authority: officialAuthority("OpenAI"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "构建 AI Agents 学习路径",
      titleEn: "Building Agents",
      provider: "OpenAI Developers",
      language: "English",
      level: "Intermediate",
      format: "Learning track",
      topics: ["Agent architecture", "tools", "guardrails", "orchestration", "evaluation"],
      url: "https://developers.openai.com/tracks/building-agents",
      accessed: "2026-08-22",
      accessNote: "Free documentation track",
      authority: officialAuthority("OpenAI Developers"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "构建 AI Agents 实用指南",
      titleEn: "A Practical Guide to Building AI Agents",
      provider: "OpenAI",
      language: "English",
      level: "Intermediate",
      format: "Online guide",
      topics: ["Agent design", "tools", "instructions", "guardrails", "deployment considerations"],
      url: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents",
      accessed: "2026-08-22",
      accessNote: "Free guide",
      authority: officialAuthority("OpenAI"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "Claude Academy",
      titleEn: "Claude Academy",
      provider: "Anthropic",
      language: "English",
      level: "Beginner to Advanced",
      format: "Online course",
      topics: ["AI fluency", "Claude API", "MCP", "Claude Code", "use cases"],
      url: "https://academy.claude.com/",
      accessed: "2026-08-22",
      accessNote: "Free courses; account may be required",
      authority: officialAuthority("Anthropic"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "模型上下文协议导论",
      titleEn: "Introduction to Model Context Protocol",
      provider: "Anthropic",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["MCP clients", "servers", "tools", "resources", "prompts", "modular integrations"],
      url: "https://anthropic.skilljar.com/introduction-to-model-context-protocol",
      accessed: "2026-08-22",
      accessNote: "Free course; account may be required",
      authority: officialAuthority("Anthropic"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "使用 Claude API 构建应用",
      titleEn: "Building with the Claude API",
      provider: "Anthropic",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["Claude API", "streaming", "tool use", "prompt caching", "application lifecycle"],
      url: "https://anthropic.skilljar.com/claude-with-the-anthropic-api",
      accessed: "2026-08-22",
      accessNote: "Free course; account may be required",
      authority: officialAuthority("Anthropic"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "Claude Code 实战",
      titleEn: "Claude Code in Action",
      provider: "Anthropic",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["Coding agents", "long-running tasks", "steering", "verification", "safe workflows"],
      url: "https://anthropic.skilljar.com/claude-code-in-action",
      accessed: "2026-08-22",
      accessNote: "Free course; account may be required",
      authority: officialAuthority("Anthropic"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "生成式 AI 导论",
      titleEn: "Introduction to Generative AI",
      provider: "Google Cloud Skills Boost",
      language: "English",
      level: "Beginner",
      format: "Online course",
      topics: ["Generative AI concepts", "model types", "applications", "Google tools"],
      url: "https://www.skills.google/course_templates/536",
      accessed: "2026-08-22",
      accessNote: "Course access may require a Google account; lab policies and subtitle or localization availability may vary",
      authority: officialAuthority("Google Cloud Skills Boost"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "大语言模型导论",
      titleEn: "Introduction to Large Language Models",
      provider: "Google Cloud Skills Boost",
      language: "English",
      level: "Beginner",
      format: "Online course",
      topics: ["LLM fundamentals", "prompting", "tuning", "Google AI development"],
      url: "https://www.skills.google/course_templates/539",
      accessed: "2026-08-22",
      accessNote: "Course access may require a Google account; lab policies and subtitle or localization availability may vary",
      authority: officialAuthority("Google Cloud Skills Boost"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "生成式 AI 与 Agents 基础",
      titleEn: "Introduction to Generative AI and Agents",
      provider: "Microsoft Learn",
      language: "Multilingual — English and Microsoft Learn localizations",
      level: "Beginner",
      format: "Learning module",
      topics: ["LLMs", "prompts", "generative AI", "AI agents", "responsible AI"],
      url: "https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai",
      accessed: "2026-08-22",
      accessNote: "Free Microsoft Learn module; localization availability may vary",
      authority: officialAuthority("Microsoft Learn"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "在 Azure 上开始构建 AI 应用与 Agents",
      titleEn: "Get Started with AI Applications and Agents on Azure",
      provider: "Microsoft Learn",
      language: "Multilingual — English and Microsoft Learn localizations",
      level: "Beginner to Intermediate",
      format: "Learning path",
      topics: ["Generative AI apps", "agents", "Microsoft Foundry", "text and knowledge workflows"],
      url: "https://learn.microsoft.com/en-us/training/paths/get-started-ai-apps-agents",
      accessed: "2026-08-22",
      accessNote: "Free Microsoft Learn path; localization availability may vary",
      authority: officialAuthority("Microsoft Learn"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "AI Agents 入门课程",
      titleEn: "AI Agents for Beginners",
      provider: "Microsoft Cloud Advocates",
      language: "Multilingual — English with community translations",
      level: "Beginner to Intermediate",
      format: "Open-source course",
      topics: ["Agent design patterns", "tool use", "orchestration", "memory", "multi-agent systems"],
      url: "https://github.com/microsoft/ai-agents-for-beginners",
      accessed: "2026-08-22",
      accessNote: "Free open-source curriculum; community translation coverage may vary",
      authority: officialAuthority("Microsoft Cloud Advocates"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "MCP 入门课程",
      titleEn: "MCP for Beginners",
      provider: "Microsoft",
      language: "Multilingual — English with community translations",
      level: "Beginner to Intermediate",
      format: "Open-source course",
      topics: ["MCP architecture", "clients", "servers", "tools", "security", "best practices"],
      url: "https://github.com/microsoft/mcp-for-beginners",
      accessed: "2026-08-22",
      accessNote: "Free open-source curriculum; community translation coverage may vary",
      authority: officialAuthority("Microsoft"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "AWS 生成式 AI 学习中心",
      titleEn: "AWS Skill Builder: Generative AI",
      provider: "AWS Skill Builder",
      language: "Multilingual — availability depends on the course",
      level: "Beginner to Advanced",
      format: "Learning hub / resource collection",
      topics: ["Generative AI foundations", "Amazon Bedrock", "development", "operations"],
      url: "https://skillbuilder.aws/generative-ai",
      accessed: "2026-08-22",
      accessNote: "Mix of free and subscription learning resources; language and regional availability may vary",
      authority: officialAuthority("AWS Skill Builder"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "生成式 AI 与 LLM 学习路径",
      titleEn: "Generative AI and LLM Learning Paths",
      provider: "NVIDIA",
      language: "English",
      level: "Beginner to Advanced",
      format: "Learning path",
      topics: ["Generative AI", "LLM development", "deployment", "RAG", "accelerated computing"],
      url: "https://www.nvidia.com/en-us/learn/learning-path/generative-ai-llm",
      accessed: "2026-08-22",
      accessNote: "Mix of free and paid NVIDIA training",
      authority: officialAuthority("NVIDIA"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "NVIDIA AI 学习基础资源",
      titleEn: "AI Learning Essentials",
      provider: "NVIDIA",
      language: "English",
      level: "Beginner to Intermediate",
      format: "Online course collection",
      topics: ["AI foundations", "generative AI concepts", "hands-on learning", "certifications"],
      url: "https://www.nvidia.com/en-us/learn/ai-learning-essentials",
      accessed: "2026-08-22",
      accessNote: "Mix of free and paid resources; certification terms may vary",
      authority: officialAuthority("NVIDIA"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "IBM SkillsBuild 成人学习者 AI 与技术课程",
      titleEn: "IBM SkillsBuild for Adult Learners",
      provider: "IBM SkillsBuild",
      language: "Multilingual — availability depends on the course",
      level: "Beginner",
      format: "Learning hub / resource collection",
      topics: ["AI fundamentals", "technology skills", "responsible use", "career skills"],
      url: "https://skillsbuild.org/adult-learners",
      accessed: "2026-08-22",
      accessNote: "Free online learning and credentials; language and regional availability may vary",
      authority: officialAuthority("IBM SkillsBuild"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "Hugging Face AI Agents 课程",
      titleEn: "Hugging Face Agents Course",
      provider: "Hugging Face",
      language: "Multilingual — English with community translations",
      level: "Beginner to Intermediate",
      format: "Online course",
      topics: ["Agents", "tools", "workflows", "frameworks", "evaluation", "hands-on assignments"],
      url: "https://huggingface.co/learn/agents-course/en/unit0/introduction",
      accessed: "2026-08-22",
      accessNote: "Free open course; community translation coverage may vary",
      authority: officialAuthority("Hugging Face"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "Hugging Face MCP 课程",
      titleEn: "Hugging Face MCP Course",
      provider: "Hugging Face",
      language: "Multilingual — English with community translations",
      level: "Beginner to Intermediate",
      format: "Online course",
      topics: ["MCP theory", "clients", "servers", "tools", "SDKs", "applications"],
      url: "https://huggingface.co/learn/mcp-course/en/unit0/introduction",
      accessed: "2026-08-22",
      accessNote: "Free open course; community translation coverage may vary",
      authority: officialAuthority("Hugging Face"),
      officiality: "Official provider resource"
    },
    {
      platform: "Official resources",
      titleZh: "面向开发者的 ChatGPT Prompt Engineering",
      titleEn: "ChatGPT Prompt Engineering for Developers",
      provider: "DeepLearning.AI / OpenAI",
      language: "English",
      level: "Beginner",
      format: "Online course",
      topics: ["Prompting principles", "iterative prompt development", "application patterns"],
      url: "https://www.deeplearning.ai/courses/chatgpt-prompt-eng",
      accessed: "2026-08-22",
      accessNote: "Course access may require an account; subtitle, certificate, and membership policies may vary",
      authority: "First-party course published by DeepLearning.AI in collaboration with OpenAI on DeepLearning.AI's official course platform.",
      officiality: "Joint first-party course"
    },
    {
      platform: "Official resources",
      titleZh: "Agentic AI",
      titleEn: "Agentic AI",
      provider: "DeepLearning.AI / Andrew Ng",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["Agentic workflows", "reflection", "tool use", "planning", "multi-agent patterns"],
      url: "https://www.deeplearning.ai/courses/agentic-ai",
      accessed: "2026-08-22",
      accessNote: "Enrollment, pricing, and certificate policies may vary",
      authority: "First-party course by DeepLearning.AI and Andrew Ng, published on DeepLearning.AI's official course platform.",
      officiality: "Joint first-party course"
    },
    {
      platform: "Official resources",
      titleZh: "使用 LangGraph 构建 AI Agents",
      titleEn: "AI Agents in LangGraph",
      provider: "DeepLearning.AI / LangChain",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["Agent state", "persistence", "human-in-the-loop", "LangGraph workflows"],
      url: "https://www.deeplearning.ai/courses/ai-agents-in-langgraph",
      accessed: "2026-08-22",
      accessNote: "Course access may require an account; certificate and membership policies may vary",
      authority: "First-party course published by DeepLearning.AI in collaboration with LangChain on DeepLearning.AI's official course platform.",
      officiality: "Joint first-party course"
    },
    {
      platform: "Official resources",
      titleZh: "使用 crewAI 构建多 Agent 系统",
      titleEn: "Multi AI Agent Systems with crewAI",
      provider: "DeepLearning.AI / crewAI",
      language: "English",
      level: "Intermediate",
      format: "Online course",
      topics: ["Role-based agents", "memory", "tools", "collaboration", "multi-step tasks"],
      url: "https://www.deeplearning.ai/courses/multi-ai-agent-systems-with-crewai",
      accessed: "2026-08-22",
      accessNote: "Course access may require an account; certificate and membership policies may vary",
      authority: "First-party course published by DeepLearning.AI in collaboration with crewAI on DeepLearning.AI's official course platform.",
      officiality: "Joint first-party course"
    },
    {
      platform: "YouTube",
      titleZh: "Transformer：大语言模型背后的技术",
      titleEn: "Transformers, the Tech Behind LLMs | Deep Learning Chapter 5",
      provider: "3Blue1Brown",
      language: "English",
      level: "Beginner",
      format: "Visual explainer · 27:14",
      topics: ["LLM foundations", "Transformers", "embeddings", "neural networks", "text generation"],
      url: "https://www.youtube.com/watch?v=wjZofJX0v4M",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published by the verified 3Blue1Brown channel, known for rigorous mathematical visualizations; YouTube metadata was read back directly.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "逐步理解 Transformer 中的注意力机制",
      titleEn: "Attention in Transformers, Step by Step | Deep Learning Chapter 6",
      provider: "3Blue1Brown",
      language: "English",
      level: "Beginner to Intermediate",
      format: "Visual explainer · 26:09",
      topics: ["Attention", "Q/K/V vectors", "softmax", "multi-head attention", "Transformer internals"],
      url: "https://www.youtube.com/watch?v=eMlx5fFNoYc",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published by the verified 3Blue1Brown channel; it is a first-party visual explanation, not a repost.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "大语言模型导论（一小时演讲）",
      titleEn: "Intro to Large Language Models",
      provider: "Andrej Karpathy",
      language: "English",
      level: "Beginner to Intermediate",
      format: "Technical talk · 59:48",
      topics: ["LLM training", "inference", "capabilities", "limitations", "security", "model ecosystem"],
      url: "https://www.youtube.com/watch?v=zjkBMFhNj_g",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published on Andrej Karpathy's own channel. Karpathy is a widely recognized AI researcher and educator; metadata was read back directly.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "像 ChatGPT 一样的大语言模型深度解析",
      titleEn: "Deep Dive into LLMs like ChatGPT",
      provider: "Andrej Karpathy",
      language: "English",
      level: "Intermediate",
      format: "Long-form technical course · 3:31:23",
      topics: ["Tokenization", "pretraining", "post-training", "evaluation", "inference", "multimodality", "security"],
      url: "https://www.youtube.com/watch?v=7xTGNNLPyMI",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published on Andrej Karpathy's own channel and presented as a long-form first-party technical course.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "从零用代码构建 GPT",
      titleEn: "Let's Build GPT: From Scratch, in Code, Spelled Out",
      provider: "Andrej Karpathy",
      language: "English",
      level: "Intermediate",
      format: "Coding course · 1:56:20",
      topics: ["Transformer implementation", "self-attention", "language modeling", "PyTorch", "training"],
      url: "https://www.youtube.com/watch?v=kCc8FmEb1nY",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published on Andrej Karpathy's own channel; it implements a small GPT model step by step rather than only describing it.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "我如何使用大语言模型",
      titleEn: "How I Use LLMs",
      provider: "Andrej Karpathy",
      language: "English",
      level: "Beginner to Intermediate",
      format: "Practical lecture · 2:11:12",
      topics: ["Practical LLM use", "prompting", "coding", "multimodal workflows", "limitations", "safety"],
      url: "https://www.youtube.com/watch?v=EWvNQjAaOHw",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published on Andrej Karpathy's own channel; it demonstrates practical workflows while discussing limits and failure modes.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "AI 红队测试 101 完整课程",
      titleEn: "AI Red Teaming 101 – Full Course (Episodes 1-10)",
      provider: "Microsoft Developer",
      language: "English",
      level: "Beginner to Intermediate",
      format: "10-episode security course · 1:17:25",
      topics: ["AI security", "red teaming", "adversarial testing", "prompt injection", "responsible AI"],
      url: "https://www.youtube.com/watch?v=DwFVhFdD2fs",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published by the verified Microsoft Developer channel; direct YouTube metadata confirmed the full-course title and duration.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "MCP 入门完整课程（第1至11课）",
      titleEn: "Full Course (Lessons 1-11) MCP for Beginners",
      provider: "Microsoft Developer",
      language: "English",
      level: "Beginner to Intermediate",
      format: "11-lesson course · 50:46",
      topics: ["MCP clients", "servers", "tools", "resources", "prompts", "security", "agent integration"],
      url: "https://www.youtube.com/watch?v=VfZlglOWWZw",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published by the verified Microsoft Developer channel and paired with Microsoft's open MCP curriculum.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "Hugging Face Agents 课程介绍与答疑",
      titleEn: "Welcome to the Agents Course! Introduction and Q&A",
      provider: "Hugging Face",
      language: "English",
      level: "Beginner",
      format: "Course orientation and Q&A · 58:08",
      topics: ["AI Agents course structure", "tools", "frameworks", "assignments", "community learning"],
      url: "https://www.youtube.com/watch?v=iLVyYDbdSmM",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published on the Hugging Face channel as the first-party orientation for its open Agents Course.",
      officiality: "First-party channel publication"
    },
    {
      platform: "YouTube",
      titleZh: "OpenAI Agent Builder 导论",
      titleEn: "Intro to Agent Builder",
      provider: "OpenAI",
      language: "English",
      level: "Beginner",
      format: "Official product introduction · 5:29",
      topics: ["Agent Builder", "agent workflows", "tools", "deployment", "OpenAI platform"],
      url: "https://www.youtube.com/watch?v=44eFf-tRiSg",
      accessed: "2026-08-22",
      accessNote: youtubeAccess,
      authority: "Published by the verified OpenAI channel; it is a first-party product introduction, not an independent review.",
      officiality: "First-party channel publication"
    },
    {
      platform: "Bilibili",
      titleZh: "人工智能导论（全集）",
      titleEn: "Introduction to Artificial Intelligence (Complete Course)",
      provider: "Zhongyu Wei / Fudan University Data Intelligence and Social Computing Lab (uploader: Fudan DISC Zhongyu Wei)",
      language: "Chinese — Mandarin",
      level: "Beginner to Intermediate",
      format: "74-part complete undergraduate recording / MOOC collection",
      topics: ["AI foundations", "search and heuristic search", "game playing", "constraint satisfaction", "Markov decision processes", "classical AI"],
      url: "https://www.bilibili.com/video/BV1M24y1x7mM",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published by an account representing the instructor and lab. The description identifies Fudan University's Data Intelligence and Social Computing Lab as the course producer, Associate Professor Zhongyu Wei as the instructor, and links the XuetangX course. The account is not Fudan University's institution-wide official account, but it is a first-party course-team source.",
      officiality: "Course-team first-party"
    },
    {
      platform: "Bilibili",
      titleZh: "吴恩达《给所有人的AI课》（中英字幕）",
      titleEn: "AI for Everyone",
      provider: "Andrew Ng / DeepLearning.AI; Bilibili uploader: GPT Chinese-English Subtitle Course Resources",
      language: "Multilingual — English audio with Chinese and English subtitles",
      level: "Beginner",
      format: "35-part course collection with unofficial bilingual subtitles",
      topics: ["AI foundations", "machine learning and deep learning literacy", "data", "AI project workflow", "AI strategy", "ethics and social impact"],
      url: "https://www.bilibili.com/video/BV1yC4y127uj",
      accessed: "2026-08-22",
      accessNote: `${bilibiliAccess} This is a non-official repost with no authorization statement found on the page.`,
      authority: "The original course by Andrew Ng and DeepLearning.AI is widely recognized, and the collection links the original Coursera course and follows its 35-part structure. However, the Bilibili uploader is not Andrew Ng, DeepLearning.AI, or a verified official account, and the page shows no authorization statement; this item is therefore explicitly classified as a non-official repost.",
      officiality: "Non-official repost"
    },
    {
      platform: "Bilibili",
      titleZh: "第一讲：一堂课搞懂生成式人工智能的技术突破与未来发展（李宏毅2025《机器学习》）",
      titleEn: "Lecture 1: Understanding the Breakthroughs and Future of Generative AI (Hung-yi Lee 2025 Machine Learning)",
      provider: "Hung-yi Lee (instructor); A Graduate Student Who Knows a Bit of Everything (authorized uploader)",
      language: "Chinese — Mandarin with Traditional Chinese slides",
      level: "Beginner to Intermediate",
      format: "Single lecture in a 27-part university course collection (Part 1)",
      topics: ["machine learning", "generative AI", "LLMs", "technical evolution", "modern AI foundations"],
      url: "https://www.bilibili.com/video/BV1aiADewEBC?p=1",
      accessed: "2026-08-22",
      accessNote: `${bilibiliAccess} The third-party uploader states that Hung-yi Lee authorized the repost.`,
      authority: "The account is not affiliated with Hung-yi Lee or National Taiwan University, but the collection description explicitly states that the uploader contacted Hung-yi Lee and received permission to repost, and it links his 2025 course page on the National Taiwan University Department of Electrical Engineering website.",
      officiality: "Authorized repost"
    },
    {
      platform: "Bilibili",
      titleZh: "百度零基础深度学习集训营",
      titleEn: "Baidu Deep Learning Bootcamp for Absolute Beginners",
      provider: "PaddlePaddle (Baidu PaddlePaddle official account)",
      language: "Chinese — Mandarin",
      level: "Beginner to Intermediate",
      format: "21-part structured course collection with lectures and practice",
      topics: ["deep learning", "neural networks", "NumPy", "computer vision", "natural language processing", "recommender systems", "PaddlePaddle"],
      url: "https://www.bilibili.com/video/BV1zJ411579R",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published by PaddlePaddle's official vendor account on Bilibili. The description identifies it as an official course created by Baidu PaddlePaddle and presents a structured deep-learning curriculum.",
      officiality: "Vendor official account"
    },
    {
      platform: "Bilibili",
      titleZh: "Softmax回归＋损失函数＋图片分类数据集【动手学深度学习v2】",
      titleEn: "Softmax Regression, Loss Functions, and Image Classification Datasets (Dive into Deep Learning v2)",
      provider: "Mu Li (uploader: Learn AI with Mu Li)",
      language: "Chinese — Mandarin with English code and terminology",
      level: "Beginner to Intermediate",
      format: "Six-part chapter collection covering theory, from-scratch and concise implementations, and Q&A",
      topics: ["machine learning", "deep-learning foundations", "Softmax regression", "loss functions", "image classification", "code implementation"],
      url: "https://www.bilibili.com/video/BV1K64y1Q7wu",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published first-party on Mu Li's teaching account, Learn AI with Mu Li. The description links the official Dive into Deep Learning v2 course page and online textbook, combining an established textbook, author-led instruction, and reproducible implementation work.",
      officiality: "Course-team first-party"
    },
    {
      platform: "Bilibili",
      titleZh: "Transformer【动手学深度学习v2】",
      titleEn: "Transformer (Dive into Deep Learning v2)",
      provider: "Mu Li (uploader: Learn AI with Mu Li)",
      language: "Chinese — Mandarin with English code and terminology",
      level: "Intermediate",
      format: "Four-part chapter collection covering theory, code, and Q&A",
      topics: ["Transformers", "attention", "multi-head attention", "encoder-decoder architecture", "deep-learning implementation"],
      url: "https://www.bilibili.com/video/BV1Kq4y1H7FL",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published first-party on Mu Li's teaching account as part of Dive into Deep Learning v2. The description links the course page and online textbook, and the video covers Transformer theory, code, and Q&A.",
      officiality: "Course-team first-party"
    },
    {
      platform: "Bilibili",
      titleZh: "GPT、GPT-2、GPT-3论文精读",
      titleEn: "GPT, GPT-2, and GPT-3 Paper Walkthrough",
      provider: "Mu Li (uploader: Learn AI with Mu Li)",
      language: "Chinese — Mandarin discussion of English-language papers",
      level: "Intermediate to Advanced",
      format: "Single paper-walkthrough video",
      topics: ["LLMs", "GPT series", "autoregressive language models", "pretraining", "few-shot learning", "scaling"],
      url: "https://www.bilibili.com/video/BV1AF411b7xQ",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published first-party on Mu Li's own account. The description links his public mli/paper-reading repository and teaches directly from the original GPT-series papers; it is a well-known technical paper-reading resource on Bilibili.",
      officiality: "Course-team first-party"
    },
    {
      platform: "Bilibili",
      titleZh: "InstructGPT论文精读",
      titleEn: "InstructGPT Paper Walkthrough",
      provider: "Mu Li (uploader: Learn AI with Mu Li)",
      language: "Chinese — Mandarin discussion of an English-language paper",
      level: "Intermediate to Advanced",
      format: "Single paper-walkthrough video",
      topics: ["LLMs", "instruction tuning", "RLHF", "human preferences", "reward models", "PPO", "model alignment"],
      url: "https://www.bilibili.com/video/BV1hd4y187CR",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published first-party on Mu Li's own account. The description links his public mli/paper-reading repository and walks through the original OpenAI InstructGPT paper, providing an authoritative secondary explanation of the modern LLM alignment process.",
      officiality: "Course-team first-party"
    },
    {
      platform: "Bilibili",
      titleZh: "第二讲：一堂课搞懂AI Agent的原理（李宏毅2025《机器学习》）",
      titleEn: "Lecture 2: Understanding How AI Agents Work (Hung-yi Lee 2025 Machine Learning)",
      provider: "Hung-yi Lee (instructor); A Graduate Student Who Knows a Bit of Everything (authorized uploader)",
      language: "Chinese — Mandarin with Traditional Chinese slides",
      level: "Beginner to Intermediate",
      format: "Single lecture in a 27-part university course collection (Part 6)",
      topics: ["AI agents", "behavior adjustment", "tool use", "task planning", "generative AI", "LLMs"],
      url: "https://www.bilibili.com/video/BV1aiADewEBC?p=6",
      accessed: "2026-08-22",
      accessNote: `${bilibiliAccess} The third-party uploader states that Hung-yi Lee authorized the repost.`,
      authority: "This is an original university-course lecture by Hung-yi Lee. Although a third-party Bilibili uploader posted the collection, its description explicitly states that Hung-yi Lee granted repost permission and links the National Taiwan University course page; it is therefore classified as an authorized repost, not an official account publication.",
      officiality: "Authorized repost"
    },
    {
      platform: "Bilibili",
      titleZh: "使用AgentScope 2.0 Harness框架构建分布式、企业级智能体",
      titleEn: "Building Distributed, Enterprise-Grade Agents with the AgentScope 2.0 Harness Framework",
      provider: "Alibaba Cloud Native",
      language: "Chinese — Mandarin with English framework and code terminology",
      level: "Intermediate to Advanced",
      format: "Single technical talk and framework implementation video",
      topics: ["AI agents", "AgentScope 2.0", "Harness", "distributed agents", "enterprise agent architecture", "multi-agent systems"],
      url: "https://www.bilibili.com/video/BV1P9gf6qE3y",
      accessed: "2026-08-22",
      accessNote: bilibiliAccess,
      authority: "Published by the official Alibaba Cloud Native vendor account. The topic directly covers Alibaba's open-source AgentScope 2.0 framework and serves as an official engineering-focused follow-up to the conceptual Hung-yi Lee lecture.",
      officiality: "Vendor official account"
    }
  ];

  const normalized = rawResources.map((item, index) => ({
    id: `learning-${String(index + 1).padStart(3, "0")}`,
    ...item
  }));

  window.COURSE_PARTS = window.COURSE_PARTS || {};
  window.COURSE_PARTS.learningResources = normalized;
})();
