(() => {
  "use strict";

  const rawResources = [
  {
    "platform": "官方课程",
    "titleZh": "OpenAI Academy",
    "titleEn": "OpenAI Academy",
    "provider": "OpenAI",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "在线课程",
    "topics": "AI literacy, prompting, data analysis, workflow automation, responsible use",
    "url": "https://academy.openai.com/",
    "accessed": "2026-08-22",
    "accessNote": "Free public learning hub; regional access may vary",
    "authority": "由 OpenAI 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "构建 AI Agents 学习路径",
    "titleEn": "Building Agents",
    "provider": "OpenAI Developers",
    "language": "English",
    "level": "Intermediate",
    "format": "学习路径",
    "topics": "Agent architecture, tools, guardrails, orchestration, evaluation",
    "url": "https://developers.openai.com/tracks/building-agents",
    "accessed": "2026-08-22",
    "accessNote": "Free documentation track",
    "authority": "由 OpenAI Developers 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "构建 AI Agents 实用指南",
    "titleEn": "A Practical Guide to Building AI Agents",
    "provider": "OpenAI",
    "language": "English",
    "level": "Intermediate",
    "format": "在线指南",
    "topics": "Agent design, tools, instructions, guardrails, deployment considerations",
    "url": "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/",
    "accessed": "2026-08-22",
    "accessNote": "Free guide",
    "authority": "由 OpenAI 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "Claude Academy",
    "titleEn": "Claude Academy",
    "provider": "Anthropic",
    "language": "English",
    "level": "Beginner to advanced",
    "format": "在线课程",
    "topics": "AI fluency, Claude API, MCP, Claude Code, use cases",
    "url": "https://academy.claude.com/",
    "accessed": "2026-08-22",
    "accessNote": "Free courses; account may be required",
    "authority": "由 Anthropic 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "模型上下文协议导论",
    "titleEn": "Introduction to Model Context Protocol",
    "provider": "Anthropic",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "MCP clients, servers, tools, resources, prompts, modular integrations",
    "url": "https://anthropic.skilljar.com/introduction-to-model-context-protocol",
    "accessed": "2026-08-22",
    "accessNote": "Free course; account may be required",
    "authority": "由 Anthropic 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "使用 Claude API 构建应用",
    "titleEn": "Building with the Claude API",
    "provider": "Anthropic",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "Claude API, streaming, tool use, prompt caching, application lifecycle",
    "url": "https://anthropic.skilljar.com/claude-with-the-anthropic-api",
    "accessed": "2026-08-22",
    "accessNote": "Free course; account may be required",
    "authority": "由 Anthropic 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "Claude Code 实战",
    "titleEn": "Claude Code in Action",
    "provider": "Anthropic",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "Coding agents, long-running tasks, steering, verification, safe workflows",
    "url": "https://anthropic.skilljar.com/claude-code-in-action",
    "accessed": "2026-08-22",
    "accessNote": "Free course; account may be required",
    "authority": "由 Anthropic 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "生成式 AI 导论",
    "titleEn": "Introduction to Generative AI",
    "provider": "Google Cloud Skills Boost",
    "language": "English; subtitles/localization may vary",
    "level": "Beginner",
    "format": "在线课程",
    "topics": "Generative AI concepts, model types, applications, Google tools",
    "url": "https://www.skills.google/course_templates/536",
    "accessed": "2026-08-22",
    "accessNote": "Course access may require a Google account; lab policies vary",
    "authority": "由 Google Cloud Skills Boost 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "大语言模型导论",
    "titleEn": "Introduction to Large Language Models",
    "provider": "Google Cloud Skills Boost",
    "language": "English; subtitles/localization may vary",
    "level": "Beginner",
    "format": "在线课程",
    "topics": "LLM fundamentals, prompting, tuning, Google AI development",
    "url": "https://www.skills.google/course_templates/539",
    "accessed": "2026-08-22",
    "accessNote": "Course access may require a Google account; lab policies vary",
    "authority": "由 Google Cloud Skills Boost 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "生成式 AI 与 Agents 基础",
    "titleEn": "Introduction to Generative AI and Agents",
    "provider": "Microsoft Learn",
    "language": "English and Microsoft Learn localizations",
    "level": "Beginner",
    "format": "学习模块",
    "topics": "LLMs, prompts, generative AI, AI agents, responsible AI",
    "url": "https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai/",
    "accessed": "2026-08-22",
    "accessNote": "Free Microsoft Learn module",
    "authority": "由 Microsoft Learn 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "在 Azure 上开始构建 AI 应用与 Agents",
    "titleEn": "Get Started with AI Applications and Agents on Azure",
    "provider": "Microsoft Learn",
    "language": "English and Microsoft Learn localizations",
    "level": "Beginner to intermediate",
    "format": "学习路径",
    "topics": "Generative AI apps, agents, Microsoft Foundry, text and knowledge workflows",
    "url": "https://learn.microsoft.com/en-us/training/paths/get-started-ai-apps-agents/",
    "accessed": "2026-08-22",
    "accessNote": "Free Microsoft Learn path",
    "authority": "由 Microsoft Learn 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "AI Agents 入门课程",
    "titleEn": "AI Agents for Beginners",
    "provider": "Microsoft Cloud Advocates",
    "language": "English with community translations",
    "level": "Beginner to intermediate",
    "format": "开源课程",
    "topics": "Agent design patterns, tool use, orchestration, memory, multi-agent systems",
    "url": "https://github.com/microsoft/ai-agents-for-beginners",
    "accessed": "2026-08-22",
    "accessNote": "Free open-source curriculum",
    "authority": "由 Microsoft Cloud Advocates 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "MCP 入门课程",
    "titleEn": "MCP for Beginners",
    "provider": "Microsoft",
    "language": "English with community translations",
    "level": "Beginner to intermediate",
    "format": "开源课程",
    "topics": "MCP architecture, clients, servers, tools, security, best practices",
    "url": "https://github.com/microsoft/mcp-for-beginners/",
    "accessed": "2026-08-22",
    "accessNote": "Free open-source curriculum",
    "authority": "由 Microsoft 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "AWS 生成式 AI 学习中心",
    "titleEn": "AWS Skill Builder: Generative AI",
    "provider": "AWS Skill Builder",
    "language": "Multiple languages depending on course",
    "level": "Beginner to advanced",
    "format": "学习中心 / 资源合集",
    "topics": "Generative AI foundations, Amazon Bedrock, development, operations",
    "url": "https://skillbuilder.aws/generative-ai",
    "accessed": "2026-08-22",
    "accessNote": "Mix of free and subscription learning resources",
    "authority": "由 AWS Skill Builder 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "生成式 AI 与 LLM 学习路径",
    "titleEn": "Generative AI and LLM Learning Paths",
    "provider": "NVIDIA",
    "language": "English",
    "level": "Beginner to advanced",
    "format": "学习路径",
    "topics": "Generative AI, LLM development, deployment, RAG, accelerated computing",
    "url": "https://www.nvidia.com/en-us/learn/learning-path/generative-ai-llm/",
    "accessed": "2026-08-22",
    "accessNote": "Mix of free and paid NVIDIA training",
    "authority": "由 NVIDIA 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "NVIDIA AI 学习基础资源",
    "titleEn": "AI Learning Essentials",
    "provider": "NVIDIA",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "在线课程",
    "topics": "AI foundations, generative AI concepts, hands-on learning, certifications",
    "url": "https://www.nvidia.com/en-us/learn/ai-learning-essentials/",
    "accessed": "2026-08-22",
    "accessNote": "Mix of free and paid resources",
    "authority": "由 NVIDIA 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "IBM SkillsBuild 成人学习者 AI 与技术课程",
    "titleEn": "IBM SkillsBuild for Adult Learners",
    "provider": "IBM SkillsBuild",
    "language": "Multiple languages depending on course",
    "level": "Beginner",
    "format": "学习中心 / 资源合集",
    "topics": "AI fundamentals, technology skills, responsible use, career skills",
    "url": "https://skillsbuild.org/adult-learners",
    "accessed": "2026-08-22",
    "accessNote": "Free online learning and credentials",
    "authority": "由 IBM SkillsBuild 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "Hugging Face AI Agents 课程",
    "titleEn": "Hugging Face Agents Course",
    "provider": "Hugging Face",
    "language": "English with community translations",
    "level": "Beginner to intermediate",
    "format": "在线课程",
    "topics": "Agents, tools, workflows, frameworks, evaluation, hands-on assignments",
    "url": "https://huggingface.co/learn/agents-course/en/unit0/introduction",
    "accessed": "2026-08-22",
    "accessNote": "Free open course",
    "authority": "由 Hugging Face 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "Hugging Face MCP 课程",
    "titleEn": "Hugging Face MCP Course",
    "provider": "Hugging Face",
    "language": "English with community translations",
    "level": "Beginner to intermediate",
    "format": "在线课程",
    "topics": "MCP theory, clients, servers, tools, SDKs, applications",
    "url": "https://huggingface.co/learn/mcp-course/en/unit0/introduction",
    "accessed": "2026-08-22",
    "accessNote": "Free open course",
    "authority": "由 Hugging Face 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "发布方官方资源"
  },
  {
    "platform": "官方课程",
    "titleZh": "面向开发者的 ChatGPT Prompt Engineering",
    "titleEn": "ChatGPT Prompt Engineering for Developers",
    "provider": "DeepLearning.AI / OpenAI",
    "language": "English; subtitles may vary",
    "level": "Beginner",
    "format": "在线课程",
    "topics": "Prompting principles, iterative prompt development, application patterns",
    "url": "https://www.deeplearning.ai/courses/chatgpt-prompt-eng",
    "accessed": "2026-08-22",
    "accessNote": "Course access may require an account; certificate/membership policies vary",
    "authority": "由 DeepLearning.AI / OpenAI 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "合作方联合课程"
  },
  {
    "platform": "官方课程",
    "titleZh": "Agentic AI",
    "titleEn": "Agentic AI",
    "provider": "DeepLearning.AI / Andrew Ng",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "Agentic workflows, reflection, tool use, planning, multi-agent patterns",
    "url": "https://www.deeplearning.ai/courses/agentic-ai",
    "accessed": "2026-08-22",
    "accessNote": "Enrollment and certificate policies may vary",
    "authority": "由 DeepLearning.AI / Andrew Ng 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "合作方联合课程"
  },
  {
    "platform": "官方课程",
    "titleZh": "使用 LangGraph 构建 AI Agents",
    "titleEn": "AI Agents in LangGraph",
    "provider": "DeepLearning.AI / LangChain",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "Agent state, persistence, human-in-the-loop, LangGraph workflows",
    "url": "https://www.deeplearning.ai/courses/ai-agents-in-langgraph",
    "accessed": "2026-08-22",
    "accessNote": "Course access may require an account; certificate/membership policies vary",
    "authority": "由 DeepLearning.AI / LangChain 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "合作方联合课程"
  },
  {
    "platform": "官方课程",
    "titleZh": "使用 crewAI 构建多 Agent 系统",
    "titleEn": "Multi AI Agent Systems with crewAI",
    "provider": "DeepLearning.AI / crewAI",
    "language": "English",
    "level": "Intermediate",
    "format": "在线课程",
    "topics": "Role-based agents, memory, tools, collaboration, multi-step tasks",
    "url": "https://www.deeplearning.ai/courses/multi-ai-agent-systems-with-crewai",
    "accessed": "2026-08-22",
    "accessNote": "Course access may require an account; certificate/membership policies vary",
    "authority": "由 DeepLearning.AI / crewAI 官方网站或官方课程平台发布的一手学习资源。",
    "officiality": "合作方联合课程"
  },
  {
    "platform": "YouTube",
    "titleZh": "Transformer：大语言模型背后的技术",
    "titleEn": "Transformers, the Tech Behind LLMs | Deep Learning Chapter 5",
    "provider": "3Blue1Brown",
    "language": "English",
    "level": "Beginner",
    "format": "Visual explainer · 27:14",
    "topics": "LLM foundations, Transformers, embeddings, neural networks, text generation",
    "url": "https://www.youtube.com/watch?v=wjZofJX0v4M",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published by the verified 3Blue1Brown channel, known for rigorous mathematical visualizations; YouTube metadata was read back directly.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "逐步理解 Transformer 中的注意力机制",
    "titleEn": "Attention in Transformers, Step by Step | Deep Learning Chapter 6",
    "provider": "3Blue1Brown",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "Visual explainer · 26:09",
    "topics": "Attention, Q/K/V vectors, softmax, multi-head attention, Transformer internals",
    "url": "https://www.youtube.com/watch?v=eMlx5fFNoYc",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published by the verified 3Blue1Brown channel; it is a first-party visual explanation, not a repost.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "大语言模型导论（一小时演讲）",
    "titleEn": "Intro to Large Language Models",
    "provider": "Andrej Karpathy",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "Technical talk · 59:48",
    "topics": "LLM training, inference, capabilities, limitations, security, model ecosystem",
    "url": "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published on Andrej Karpathy's own channel. Karpathy is a widely recognized AI researcher and educator; metadata was read back directly.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "像 ChatGPT 一样的大语言模型深度解析",
    "titleEn": "Deep Dive into LLMs like ChatGPT",
    "provider": "Andrej Karpathy",
    "language": "English",
    "level": "Intermediate",
    "format": "Long-form technical course · 3:31:23",
    "topics": "Tokenization, pretraining, post-training, evaluation, inference, multimodality, security",
    "url": "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published on Andrej Karpathy's own channel and presented as a long-form first-party technical course.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "从零用代码构建 GPT",
    "titleEn": "Let's Build GPT: From Scratch, in Code, Spelled Out",
    "provider": "Andrej Karpathy",
    "language": "English",
    "level": "Intermediate",
    "format": "Coding course · 1:56:20",
    "topics": "Transformer implementation, self-attention, language modeling, PyTorch, training",
    "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published on Andrej Karpathy's own channel; it implements a small GPT model step by step rather than only describing it.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "我如何使用大语言模型",
    "titleEn": "How I Use LLMs",
    "provider": "Andrej Karpathy",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "Practical lecture · 2:11:12",
    "topics": "Practical LLM use, prompting, coding, multimodal workflows, limitations, safety",
    "url": "https://www.youtube.com/watch?v=EWvNQjAaOHw",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published on Andrej Karpathy's own channel; it demonstrates practical workflows while discussing limits and failure modes.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "AI 红队测试 101 完整课程",
    "titleEn": "AI Red Teaming 101 – Full Course (Episodes 1-10)",
    "provider": "Microsoft Developer",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "10-episode security course · 1:17:25",
    "topics": "AI security, red teaming, adversarial testing, prompt injection, responsible AI",
    "url": "https://www.youtube.com/watch?v=DwFVhFdD2fs",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published by the verified Microsoft Developer channel; direct YouTube metadata confirmed the full-course title and duration.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "MCP 入门完整课程（第1至11课）",
    "titleEn": "Full Course (Lessons 1-11) MCP for Beginners",
    "provider": "Microsoft Developer",
    "language": "English",
    "level": "Beginner to intermediate",
    "format": "11-lesson course · 50:46",
    "topics": "MCP clients, servers, tools, resources, prompts, security, agent integration",
    "url": "https://www.youtube.com/watch?v=VfZlglOWWZw",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published by the verified Microsoft Developer channel and paired with Microsoft's open MCP curriculum.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "Hugging Face Agents 课程介绍与答疑",
    "titleEn": "Welcome to the Agents Course! Introduction and Q&A",
    "provider": "Hugging Face",
    "language": "English",
    "level": "Beginner",
    "format": "Course orientation and Q&A · 58:08",
    "topics": "AI Agents course structure, tools, frameworks, assignments, community learning",
    "url": "https://www.youtube.com/watch?v=iLVyYDbdSmM",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published on the Hugging Face channel as the first-party orientation for its open Agents Course.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "YouTube",
    "titleZh": "OpenAI Agent Builder 导论",
    "titleEn": "Intro to Agent Builder",
    "provider": "OpenAI",
    "language": "English",
    "level": "Beginner",
    "format": "Official product introduction · 5:29",
    "topics": "Agent Builder, agent workflows, tools, deployment, OpenAI platform",
    "url": "https://www.youtube.com/watch?v=44eFf-tRiSg",
    "accessed": "2026-08-22",
    "accessNote": "YouTube 公开页面；地区、登录要求与字幕可用性可能变化。",
    "authority": "Published by the verified OpenAI channel; it is a first-party product introduction, not an independent review.",
    "officiality": "发布频道官方内容"
  },
  {
    "platform": "Bilibili",
    "titleZh": "人工智能导论（全集）",
    "titleEn": "Introduction to Artificial Intelligence (Complete Course)",
    "provider": "魏忠钰 / 复旦大学数据智能与社会计算实验室（UP主：复旦DISC魏忠钰）",
    "language": "中文（普通话）",
    "level": "本科入门—中级",
    "format": "74集完整课程合集（本科录播/MOOC）",
    "topics": "AI基础、搜索与启发式搜索、博弈、约束满足、马尔可夫决策过程、经典人工智能",
    "url": "https://www.bilibili.com/video/BV1M24y1x7mM/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "主讲教师/实验室身份账号发布；视频简介明确称课程由复旦大学数据智能与社会计算实验室推出、主讲人为复旦大学魏忠钰副教授，并链接学堂在线课程；不是复旦大学校级官方账号，但属于课程团队一手来源。",
    "officiality": "课程团队一手发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "吴恩达《给所有人的AI课》（中英字幕）",
    "titleEn": "AI for Everyone",
    "provider": "Andrew Ng（吴恩达）/ DeepLearning.AI；B站UP主：GPT中英字幕课程资源",
    "language": "英语原声；中英双语字幕",
    "level": "零基础—入门",
    "format": "35集课程合集（非官方双语字幕转载）",
    "topics": "AI基础、机器学习与深度学习通识、数据、AI项目流程、AI战略、伦理与社会影响",
    "url": "https://www.bilibili.com/video/BV1yC4y127uj/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "课程原作者吴恩达及DeepLearning.AI具有公认权威性，合集简介链接Coursera原课且35个分集与课程结构相符；但B站UP主不是吴恩达、DeepLearning.AI或其已核实官方账号，页面未见授权声明，故明确标为非官方转载。",
    "officiality": "非官方转载（未见授权声明）"
  },
  {
    "platform": "Bilibili",
    "titleZh": "第一讲：一堂课搞懂生成式人工智能的技术突破与未来发展（李宏毅2025《机器学习》）",
    "titleEn": "Lecture 1: Understanding the Breakthroughs and Future of Generative AI (Hung-yi Lee 2025 Machine Learning)",
    "provider": "李宏毅（授课）；啥都会一点的研究生（获授权转载）",
    "language": "中文（普通话；繁体中文课件）",
    "level": "入门—中级",
    "format": "27集课程合集中的单讲（P1；大学课程讲座）",
    "topics": "机器学习、生成式AI、LLM/大语言模型、技术演进、现代AI基础",
    "url": "https://www.bilibili.com/video/BV1aiADewEBC/?p=1",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "非官方但有明确授权声明：合集简介写明“已联系李宏毅老师得到转载许可”，并链接李宏毅在台湾大学电机工程学系网站上的2025课程主页；UP主不是李宏毅或台大官方账号。",
    "officiality": "已授权转载（非官方账号）"
  },
  {
    "platform": "Bilibili",
    "titleZh": "百度零基础深度学习集训营",
    "titleEn": "Baidu Deep Learning Bootcamp for Absolute Beginners",
    "provider": "飞桨PaddlePaddle（百度飞桨官方账号）",
    "language": "中文（普通话）",
    "level": "零基础—中级",
    "format": "21集系统课程合集（讲座与实践）",
    "topics": "深度学习、神经网络、NumPy、计算机视觉、自然语言处理、推荐系统、PaddlePaddle",
    "url": "https://www.bilibili.com/video/BV1zJ411579R/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "由B站“飞桨PaddlePaddle”厂商官方账号发布；视频简介明确称其为“百度飞桨精心打造的官方课程”，包含系统化深度学习课程。",
    "officiality": "厂商官方发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "Softmax回归＋损失函数＋图片分类数据集【动手学深度学习v2】",
    "titleEn": "Softmax Regression, Loss Functions, and Image Classification Datasets (Dive into Deep Learning v2)",
    "provider": "李沐（UP主：跟李沐学AI）",
    "language": "中文（普通话；代码与术语含英文）",
    "level": "入门—中级",
    "format": "6集章节合集（原理、从零实现、简洁实现、QA）",
    "topics": "机器学习、深度学习基础、Softmax回归、损失函数、图片分类、代码实现",
    "url": "https://www.bilibili.com/video/BV1K64y1Q7wu/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "李沐本人教学账号“跟李沐学AI”一手发布；简介链接《动手学深度学习v2》官方课程主页与在线教材，兼具知名教材、作者授课和可复现实作。",
    "officiality": "课程团队一手发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "Transformer【动手学深度学习v2】",
    "titleEn": "Transformer (Dive into Deep Learning v2)",
    "provider": "李沐（UP主：跟李沐学AI）",
    "language": "中文（普通话；代码与术语含英文）",
    "level": "中级",
    "format": "4集章节合集（原理、代码、QA）",
    "topics": "Transformer、注意力机制、多头注意力、编码器—解码器、深度学习代码实现",
    "url": "https://www.bilibili.com/video/BV1Kq4y1H7FL/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "李沐本人教学账号一手发布，属于《动手学深度学习v2》课程；简介同时链接课程主页和在线教材，视频包含Transformer原理、代码与答疑。",
    "officiality": "课程团队一手发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "GPT、GPT-2、GPT-3论文精读",
    "titleEn": "GPT, GPT-2, and GPT-3 Paper Walkthrough",
    "provider": "李沐（UP主：跟李沐学AI）",
    "language": "中文（普通话；讲解英文论文）",
    "level": "中级—高级",
    "format": "单集论文精读视频",
    "topics": "LLM/大语言模型、GPT系列、自回归语言模型、预训练、少样本学习、规模化",
    "url": "https://www.bilibili.com/video/BV1AF411b7xQ/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "由李沐本人账号一手发布；视频简介链接其公开的mli/paper-reading论文精读仓库，以GPT系列原始论文为讲解对象，属于B站高知名度技术精读资源。",
    "officiality": "课程团队一手发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "InstructGPT论文精读",
    "titleEn": "InstructGPT Paper Walkthrough",
    "provider": "李沐（UP主：跟李沐学AI）",
    "language": "中文（普通话；讲解英文论文）",
    "level": "中级—高级",
    "format": "单集论文精读视频",
    "topics": "LLM/大语言模型、指令微调、RLHF、人类偏好、奖励模型、PPO、模型对齐",
    "url": "https://www.bilibili.com/video/BV1hd4y187CR/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "由李沐本人账号一手发布；简介链接其mli/paper-reading公开仓库，围绕OpenAI InstructGPT原始论文逐段讲解，是理解现代LLM对齐流程的权威二手教学。",
    "officiality": "课程团队一手发布"
  },
  {
    "platform": "Bilibili",
    "titleZh": "第二讲：一堂课搞懂AI Agent的原理（李宏毅2025《机器学习》）",
    "titleEn": "Lecture 2: Understanding How AI Agents Work (Hung-yi Lee 2025 Machine Learning)",
    "provider": "李宏毅（授课）；啥都会一点的研究生（获授权转载）",
    "language": "中文（普通话；繁体中文课件）",
    "level": "入门—中级",
    "format": "27集课程合集中的单讲（P6；大学课程讲座）",
    "topics": "AI Agent/智能体、行为调整、工具使用、任务规划、生成式AI、LLM",
    "url": "https://www.bilibili.com/video/BV1aiADewEBC/?p=6",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "李宏毅大学课程原讲；B站合集虽由第三方UP主上传，但简介明确写明已联系李宏毅取得转载许可，并链接台湾大学课程主页，因此标注为“非官方账号的已授权转载”。",
    "officiality": "已授权转载（非官方账号）"
  },
  {
    "platform": "Bilibili",
    "titleZh": "使用AgentScope 2.0 Harness框架构建分布式、企业级智能体",
    "titleEn": "Building Distributed, Enterprise-Grade Agents with the AgentScope 2.0 Harness Framework",
    "provider": "阿里云云原生",
    "language": "中文（普通话；框架与代码术语含英文）",
    "level": "中级—高级",
    "format": "单场技术分享/框架实战视频",
    "topics": "AI Agent/智能体、AgentScope 2.0、Harness、分布式智能体、企业级Agent架构、多智能体系统",
    "url": "https://www.bilibili.com/video/BV1P9gf6qE3y/",
    "accessed": "2026-08-22",
    "accessNote": "Bilibili 公开页面；平台后续可能因下架、地区、登录或风控策略改变可用性。",
    "authority": "由“阿里云云原生”厂商官方账号发布，主题直接对应阿里开源AgentScope 2.0框架，适合作为李宏毅概念课之后的官方工程化进阶资源。",
    "officiality": "厂商官方发布"
  }
];

  function canonicalUrl(value) {
    const url = new URL(value);
    url.hash = "";
    const isVideo = (url.hostname === "www.youtube.com" && url.pathname === "/watch") ||
      (url.hostname === "www.bilibili.com" && url.pathname.startsWith("/video/"));
    if (!isVideo) url.search = "";
    if (url.pathname.length > 1) url.pathname = url.pathname.replace(/\/+$/, "");
    return url.toString();
  }

  const seen = new Set();
  const normalized = rawResources.flatMap(item => {
    const url = canonicalUrl(item.url);
    const key = url.replace(/\/$/, "");
    if (seen.has(key)) return [];
    seen.add(key);
    return [{
      ...item,
      topics: item.topics.split(/[，,；;、]/).map(topic => topic.trim()).filter(Boolean),
      url
    }];
  }).map((item, index) => ({ id: "learning-" + String(index + 1).padStart(3, "0"), ...item }));

  window.COURSE_PARTS = window.COURSE_PARTS || {};
  window.COURSE_PARTS.learningResources = normalized;
})();
