window.COURSE_PARTS=window.COURSE_PARTS||{}; window.COURSE_PARTS.conceptsFoundation=[
  {
    id: "generative-ai",
    cn: "生成式人工智能",
    en: "Generative Artificial Intelligence (Generative AI)",
    category: "模型与生成",
    oneLine: "生成式人工智能根据学到的数据规律生成新内容，而不是从资料库中原样取回答案。",
    professional: "生成式人工智能是一类学习数据分布，并据条件输入生成文本、图像、音频、视频或代码等内容的人工智能系统；其输出是概率生成结果。",
    plain: "它像是在大量样例中学会了表达方式，再按当前要求现场组织内容，但不保证每句话都真实。",
    life: "像厨师理解许多菜谱后按现有食材做一道新菜，而不是从冰箱拿出一盘预制成品。",
    engineer: "像根据历史变更学习规律后生成一份候选生产配置；仍需 Schema 校验、自动化测试、变更审批和上线验证。",
    misconception: "常见误解是它会复制某条训练记录，或生成得流畅就代表内容正确；实际上生成、记忆与事实核验是三件事。",
    safety: "不得把生成内容直接当作事实、授权决定或可执行代码；涉及隐私、版权和高风险操作时应核验来源并由人复核。",
    related: ["foundation-model", "large-language-model", "hallucination", "multimodal"]
  },
  {
    id: "foundation-model",
    cn: "基础模型",
    en: "Foundation Model",
    category: "模型与生成",
    oneLine: "基础模型是在广泛数据上预训练、可适配多种下游任务的通用模型。",
    professional: "基础模型通过大规模预训练获得可迁移能力，随后可借助提示、检索、微调或工具接入服务不同任务；语言模型只是其中一种形态。",
    plain: "它先获得较通用的底子，再通过说明书、资料或专项训练承担具体工作。",
    life: "像完成通识教育的学员，能继续接受法律、客服或设计等岗位培训，而不是入学时就只会一个工种。",
    engineer: "像可复用的平台服务：同一套核心通过 API、配置和适配层，可服务多个业务系统与部署环境。",
    misconception: "常见误解是基础模型等于聊天产品；聊天产品还包含界面、提示策略、检索、工具、安全控制和运营服务。",
    safety: "通用能力也会带来通用风险；上线前需按具体用途评估数据来源、偏差、权限、成本和失败方式。",
    related: ["generative-ai", "large-language-model", "fine-tuning", "prompt"]
  },
  {
    id: "large-language-model",
    cn: "大语言模型",
    en: "Large Language Model (LLM)",
    category: "模型与生成",
    oneLine: "大语言模型以大量语言数据训练，用 Token 序列建模来理解和生成语言。",
    professional: "大语言模型是参数规模和训练数据规模较大的语言模型，通常学习序列中 Token 的条件概率，并通过预训练及后续对齐获得问答、写作、编码等能力。",
    plain: "它擅长根据已有上下文续写最合适的内容，复杂能力由这种训练目标和规模共同涌现，但它不是人类式数据库。",
    life: "像读过大量材料的即兴文字搭档，能顺着上下文接话，却可能把记不清的细节说得很顺。",
    engineer: "像一个超大规模的概率序列预测服务：输入 Token 流后给出后续 Token 的分布，不受编程语言类型系统或数据库约束硬性保证。",
    misconception: "常见误解是 LLM 等于所有人工智能，或参数越多就必然更可靠；模型架构、数据、训练、推理策略和评测同样关键。",
    safety: "不要依据语气判断可信度；敏感数据是否可发送、输出能否执行以及费用如何计算，都应结合服务条款和实测确认。",
    related: ["foundation-model", "token", "transformer", "context-window"]
  },
  {
    id: "transformer",
    cn: "Transformer 架构",
    en: "Transformer",
    category: "模型架构",
    oneLine: "Transformer 用注意力机制建模序列元素之间的关系，是许多现代大模型的核心架构。",
    professional: "Transformer 以自注意力、前馈网络、残差连接和位置表示等组件处理序列，使模型能按任务约束聚合不同位置的信息，并适合并行训练。",
    plain: "处理一句话时，每个片段都能按需要关注其他片段，判断哪些上下文与当前理解最相关。",
    life: "像圆桌会议中的每个人阅读全部便笺，却只重点参考与自己议题有关的几张。",
    engineer: "像依赖图分析：当前节点会沿关系关注远处的定义、调用与状态，而不只是按顺序读取前一个字符。",
    misconception: "常见误解是 Transformer 就是 LLM；它是架构，既可用于不同模态，也不必达到大语言模型的规模。",
    safety: "注意力权重不等同于可靠解释或因果证据；模型仍受上下文长度、训练数据和计算资源限制。",
    related: ["large-language-model", "token", "context-window", "multimodal"]
  },
  {
    id: "token",
    cn: "词元",
    en: "Token",
    category: "输入与控制",
    oneLine: "Token 是模型切分和处理输入输出的基本单位，不等同于一个汉字或一个英文单词。",
    professional: "Token 是分词器将文本编码为离散标识后的序列单元，可能对应字、词的一部分、标点、空白或字节片段；计费与上下文限制常以它为单位。",
    plain: "模型先把文字切成自己词表能识别的小块，再把这些小块转换成编号处理。",
    life: "像寄件前把物品按规则分装进箱：一个词可能占一个箱，也可能被拆进几个箱。",
    engineer: "它近似解析器中的词法单元，但切分规则由模型词表决定，未必遵循自然语言单词、程序标识符或字段边界。",
    misconception: "常见误解是字数可以精确换算 Token 数；不同模型、语言、空白和编码会产生不同切分。",
    safety: "预算和截断判断应使用目标模型的官方分词器或 API 用量字段，不能依赖固定字数比例。",
    related: ["large-language-model", "context-window", "rate-limit", "inference"]
  },
  {
    id: "context-window",
    cn: "上下文窗口",
    en: "Context Window",
    category: "输入与控制",
    oneLine: "上下文窗口是模型一次推理能够纳入计算的 Token 容量边界。",
    professional: "上下文窗口限定一次请求中系统指令、对话历史、检索材料、工具结果及生成内容可占用的 Token 范围，具体输入输出如何共享额度由模型接口定义。",
    plain: "只有当前放进窗口的材料才能被这次回答直接参考；超出后需要删减、压缩或另行检索。",
    life: "像尺寸有限的办公桌：档案室再大，一次能摊开并同时对照的文件仍然有限。",
    engineer: "像内存受限的查询工作区：对象存储可保留海量日志，但一次分析只能处理当前装入工作集的部分。",
    misconception: "常见误解是长上下文等于可靠长期记忆；材料放得下不代表模型能稳定找到、正确理解或永久保存。",
    safety: "无关内容会增加成本并稀释关键信息；重要约束应明确、靠近任务并通过测试确认未被截断。",
    related: ["token", "prompt", "system-prompt", "retrieval-augmented-generation"]
  },
  {
    id: "prompt",
    cn: "提示",
    en: "Prompt",
    category: "输入与控制",
    oneLine: "Prompt 是提供给模型的任务指令、背景、数据和输出约束的组合。",
    professional: "Prompt 是推理时进入上下文的条件输入，可包含目标、角色、示例、证据、工具说明和格式要求，用于影响模型输出分布而非修改模型权重。",
    plain: "它是一份给模型的工作委托书：交代要做什么、依据什么、做到什么程度。",
    life: "像给装修师傅的施工单；只说“弄好看”与写清尺寸、材料和验收标准，结果会很不同。",
    engineer: "像提交一份 API 请求：动作、参数、前置条件和期望响应越明确，服务端解释歧义越少。",
    misconception: "常见误解是存在对所有模型和任务都有效的神奇提示词；稳定效果依赖模型、上下文、数据与评测。",
    safety: "外部文本和用户输入应视为不可信数据，不能因为被放入 Prompt 就获得指令权限。",
    related: ["system-prompt", "context-window", "temperature", "prompt-injection"]
  },
  {
    id: "system-prompt",
    cn: "系统提示",
    en: "System Prompt",
    category: "输入与控制",
    oneLine: "系统提示由应用在会话高优先级位置设置，用来规定模型的角色、规则和边界。",
    professional: "System Prompt 是消息层级中由服务或应用提供的高优先级指令，用于建立长期任务约束和行为策略；它仍是上下文的一部分，不是强制访问控制。",
    plain: "它像应用在后台先交给模型的总则，用户通常是在这套总则之下提出具体任务。",
    life: "像场馆写给工作人员的内部值班守则，比访客的临时要求优先，但真正的门禁仍要靠锁和权限系统。",
    engineer: "像应用启动时加载的策略配置：它给流程默认约束，却不能代替 IAM、网络策略或服务端参数校验。",
    misconception: "常见误解是系统提示绝不会泄露、覆盖或被绕过；自然语言约束不能构成完整安全边界。",
    safety: "密钥不得写入系统提示；高风险限制应同时由权限隔离、参数校验、沙箱和人工审批落实。",
    related: ["prompt", "context-window", "function-calling", "tool-calling"]
  },
  {
    id: "temperature",
    cn: "温度参数",
    en: "Temperature",
    category: "输入与控制",
    oneLine: "Temperature 调整采样分布的集中程度，影响输出多样性，但不代表智力或事实置信度。",
    professional: "Temperature 通常通过缩放生成 logits 改变候选 Token 的相对概率：较低值使采样更集中，较高值使分布更平坦；具体支持范围和行为由模型接口决定。",
    plain: "它控制模型是在少数高概率表达里保守选择，还是更愿意尝试低概率表达。",
    life: "像调整音乐随机播放的探索度：低时反复播放熟悉热门曲，高时更常遇到冷门曲，但不会让音响更懂音乐。",
    engineer: "像调整负载均衡器在候选后端间的探索程度，而不是提升数据质量；输入状态和候选集合不会因此变真。",
    misconception: "常见误解是温度为零就绝对可复现，或高温度更有创造力且更聪明；服务实现和其他采样因素仍可能影响结果。",
    safety: "结构化、合规或事实任务通常需要更受控的采样并配合校验；不要用温度替代评测。",
    related: ["token", "inference", "hallucination", "prompt"]
  },
  {
    id: "hallucination",
    cn: "幻觉",
    en: "Hallucination",
    category: "模型可靠性",
    oneLine: "幻觉是模型生成看似合理、实际缺乏依据或与事实矛盾的内容。",
    professional: "Hallucination 指生成结果与提供的证据、可验证事实或任务约束不一致，常见形式包括虚构来源、错误归因、数据捏造和无依据推断。",
    plain: "模型可能在不知道时继续把句子补完整，并用流畅语气掩盖信息缺口。",
    life: "像路人不愿说“不知道”，于是自信地指向一间并不存在的店。",
    engineer: "像监控面板没有查询真实指标，却根据旧缓存拼出格式正确的数值；JSON 合法不等于观测真实。",
    misconception: "常见误解是只有离谱答案才算幻觉；一个错误日期、伪造引文或未经证据支持的细节同样属于幻觉。",
    safety: "关键事实应查阅权威来源，引用应能回到原文；高风险输出必须经过独立校验和责任人确认。",
    related: ["generative-ai", "retrieval-augmented-generation", "reasoning-model", "evaluation"]
  },
  {
    id: "multimodal",
    cn: "多模态",
    en: "Multimodal",
    category: "模型与生成",
    oneLine: "多模态系统能在同一任务中处理或生成文本、图像、音频、视频等多种信息形态。",
    professional: "Multimodal 模型通过各模态的编码器、共享表示或跨模态注意力建立关联，可接受一种或多种模态并输出一种或多种模态。",
    plain: "它不仅能读文字，还可能看图、听声音或生成画面，并把这些信息合起来回答。",
    life: "像理赔员同时查看事故照片、听取录音并阅读表单，综合不同材料判断是否还缺证据。",
    engineer: "像可观测平台同时接入日志、指标和调用链，经各自采集器规范化后再做联合诊断。",
    misconception: "常见误解是支持图片输入就能准确识别所有细节；分辨率、压缩、采样和模态对齐都会造成信息损失。",
    safety: "图像和音频也可能含隐私、恶意指令或伪造内容；应验证来源、最小化采集并针对各模态单独评测。",
    related: ["foundation-model", "transformer", "embedding", "context-window"]
  },
  {
    id: "embedding",
    cn: "嵌入向量",
    en: "Embedding",
    category: "检索与知识",
    oneLine: "Embedding 把内容映射为向量，使语义或特征相近的内容在向量空间中更接近。",
    professional: "Embedding 是模型生成的稠密数值表示，编码文本、图像或其他对象的任务相关特征，可通过余弦相似度、点积或距离函数进行比较。",
    plain: "它给每段内容安排一组坐标，方便机器按含义相近程度寻找邻居。",
    life: "像把书放在一张主题地图上：烘焙书靠近甜点，网络安全书靠近密码学，而不是只按书名首字母排。",
    engineer: "像把一组审计事件提取成多维特征用于异常检测；它不是原始记录，也不是加密或权限控制。",
    misconception: "常见误解是向量保存了可完整还原的原文，或距离近就证明两者事实相同；它只表达模型学到的相似特征。",
    safety: "嵌入仍可能泄露敏感特征；应控制原文和向量的访问权限，并按实际语料评估召回偏差。",
    related: ["vector-database", "retrieval-augmented-generation", "multimodal", "token"]
  },
  {
    id: "vector-database",
    cn: "向量数据库",
    en: "Vector Database",
    category: "检索与知识",
    oneLine: "向量数据库存储并索引向量，用相似度搜索找出与查询最接近的内容。",
    professional: "Vector Database 针对高维向量提供近邻检索，并常结合原始文档引用、元数据过滤、权限控制和索引维护，为语义搜索或 RAG 提供候选结果。",
    plain: "它不是按关键词完全相等来找资料，而是优先找“意思像”的条目。",
    life: "像仓库不只按编号取货，还能按用途、材质和风格找到最相似的几件商品。",
    engineer: "像为大型文档库建立搜索索引以缩小候选集，但匹配依据是向量距离，近似索引仍可能漏掉最佳项。",
    misconception: "常见误解是向量数据库自带知识理解并能直接回答问题；它负责存储和检索，答案仍由后续系统生成或整理。",
    safety: "必须把租户与文档权限带入过滤条件，设置删除和重建流程，并用真实查询评估召回率、延迟与成本。",
    related: ["embedding", "retrieval-augmented-generation", "api", "context-window"]
  },
  {
    id: "retrieval-augmented-generation",
    cn: "检索增强生成",
    en: "Retrieval-Augmented Generation (RAG)",
    category: "检索与知识",
    oneLine: "RAG 在回答前检索外部资料并把相关证据放入上下文，而不是重新训练模型。",
    professional: "Retrieval-Augmented Generation 将查询转换、检索、排序、上下文组装与生成串联，使模型在推理时依据外部知识作答，并可附带可追溯引用。",
    plain: "它让模型先查资料再回答，资料可以更新，但查错、漏查或读错仍会导致错误。",
    life: "像开卷考试：先从允许携带的资料中翻到相关章节，再据此组织答案，而不是临考前重新上完整学期的课。",
    engineer: "像值班系统在诊断前从知识库取回对应服务版本的运行手册，再把相关段落交给分析流程，而不是重新训练系统。",
    misconception: "常见误解是 RAG 会改变模型权重或彻底消除幻觉；它只在本次推理中补充证据。",
    safety: "检索源要有权限过滤、版本和引用；外部文档是非可信输入，应防止提示注入并允许回答“证据不足”。",
    related: ["embedding", "vector-database", "context-window", "hallucination"]
  },
  {
    id: "fine-tuning",
    cn: "微调",
    en: "Fine-tuning",
    category: "模型适配与运行",
    oneLine: "微调用特定数据继续训练模型并更新权重，使其更适合目标行为或任务。",
    professional: "Fine-tuning 在预训练模型基础上以监督样本、偏好数据或参数高效方法继续优化部分或全部参数，用于调整输出风格、格式、领域行为或任务性能。",
    plain: "它不是临时给模型看一份说明，而是用成组样例改变模型以后处理同类任务的习惯。",
    life: "像通识毕业后接受一段有反馈的岗位训练，纠正会沉淀为稳定习惯，而不是每次上班前读一张便签。",
    engineer: "像用领域样本重新构建一个专用模型产物；变化固化进权重，而运行时加载配置或文档更接近 Prompt 或 RAG。",
    misconception: "常见误解是新增几份事实就应微调；需要频繁更新和引用的知识通常更适合检索。",
    safety: "训练数据应有授权、脱敏和质量审查；需评估过拟合、遗忘、偏差、部署成本和回滚方案。",
    related: ["foundation-model", "prompt", "retrieval-augmented-generation", "inference"]
  },
  {
    id: "inference",
    cn: "推理运行",
    en: "Inference",
    category: "模型适配与运行",
    oneLine: "Inference 是使用已训练模型处理新输入并产生预测或生成结果的运行阶段。",
    professional: "Inference 将输入编码后执行模型前向计算，并按解码策略生成输出；延迟、吞吐量、显存、上下文长度和采样参数共同影响服务表现与成本。",
    plain: "训练是学会能力，推理是把已经学到的能力拿来完成眼前这一单。",
    life: "像乐手结束排练后正式演出：每次演奏都要花时间和体力，但通常不会因此改写多年训练形成的技巧。",
    engineer: "像在云服务中运行已经构建好的容器镜像；构建阶段塑造产物，运行阶段用当前请求得到结果。",
    misconception: "常见误解是模型每次聊天都会从对话中自动继续训练；多数 API 推理不会即时更新模型权重。",
    safety: "应限制输入输出规模、超时和重试，记录可观测用量，并确认数据保留政策与服务失败策略。",
    related: ["fine-tuning", "temperature", "concurrency", "rate-limit"]
  },
  {
    id: "reasoning-model",
    cn: "推理模型",
    en: "Reasoning Model",
    category: "模型适配与运行",
    oneLine: "推理模型针对多步骤问题求解进行优化，常用更多推理计算来提高复杂任务表现。",
    professional: "Reasoning Model 通常经过专门训练，并在推理阶段执行中间计算、搜索或自我校验，以处理数学、代码和规划等多步骤任务；实现细节因模型而异。",
    plain: "它倾向于先分解和检查复杂问题再给结论，但思考更久不等于一定正确。",
    life: "像解复杂数独时先列候选、排除冲突并回看步骤，而不是看到题目就报出第一反应。",
    engineer: "像数据库迁移先生成计划、检查依赖并验证结果，而不是收到第一条建议就直接改生产 Schema。",
    misconception: "常见误解是可见或不可见的推理过程构成数学证明；模型仍可能沿着连贯步骤得到错误结论。",
    safety: "为任务设置计算预算、超时和验收测试；涉及权限或现实影响的决定不能只靠模型自检。",
    related: ["large-language-model", "inference", "hallucination", "tool-calling"]
  },
  {
    id: "function-calling",
    cn: "函数调用",
    en: "Function Calling",
    category: "工具与集成",
    oneLine: "Function Calling 让模型按预先定义的函数模式生成结构化调用请求，由应用决定是否执行。",
    professional: "Function Calling 向模型提供函数名称、说明和参数模式，使模型输出符合约定的函数选择与参数；宿主程序负责校验、授权、执行并把结果返回模型。",
    plain: "模型填写一张格式固定的办事单，真正受理和办事的是外部程序。",
    life: "像客服替顾客填好“改签申请”，航空公司系统仍要核验身份、余票和权限后才会改票。",
    engineer: "像客户端构造符合 OpenAPI Schema 的请求；服务端先校验字段、身份与作用域，再决定是否执行真实操作。",
    misconception: "常见误解是模型输出函数名后操作已经发生；在执行器确认并运行之前，它只是一项请求。",
    safety: "参数必须按不可信输入处理，使用白名单、最小权限、幂等设计和高风险操作审批，不能直接拼接到 shell 或 SQL。",
    related: ["tool-calling", "api", "system-prompt", "oauth"]
  },
  {
    id: "tool-calling",
    cn: "工具调用",
    en: "Tool Calling",
    category: "工具与集成",
    oneLine: "Tool Calling 让模型请求使用搜索、代码执行或业务操作等外部能力，执行权仍在宿主系统。",
    professional: "Tool Calling 是模型与外部能力交互的通用机制，涵盖函数、API、浏览器、文件和命令行等工具；运行框架负责能力暴露、调用编排、权限检查和结果回传。",
    plain: "模型能提出“请帮我查、算或操作”，但必须有外部系统实际动手并把结果告诉它。",
    life: "像项目经理向电工、会计和快递员分别下工单；经理会选择工具，但不能凭一句话让工作自动完成。",
    engineer: "像操作系统处理系统调用：调用方描述动作，受控执行层检查参数与权限后才访问文件、进程或网络。",
    misconception: "常见误解是工具越多 Agent 越强；选择错误、权限过大、返回内容不可信都会扩大失败面。",
    safety: "按任务最小化工具集合和权限，限制调用次数与成本，对外部结果防注入，并为写操作设置确认和审计。",
    related: ["function-calling", "api", "system-prompt", "reasoning-model"]
  },
  {
    id: "api",
    cn: "应用程序编程接口",
    en: "Application Programming Interface (API)",
    category: "接口与安全",
    oneLine: "API 是软件组件之间按明确契约交换请求、响应或事件的接口。",
    professional: "Application Programming Interface 定义可用操作、参数、数据格式、认证、错误语义和版本规则，可通过本地库、进程间通信或网络协议提供。",
    plain: "它规定一个程序怎样向另一个程序办事，以及双方要用什么格式说话。",
    life: "像餐厅点餐窗口：菜单列出可点项目和填写方式，顾客不需要进入厨房控制炉灶。",
    engineer: "像 REST、gRPC 或消息队列契约：调用方按稳定接口交互，不依赖服务内部实现。",
    misconception: "常见误解是 API 专指互联网网址；操作系统调用、库函数和设备接口也可以是 API。",
    safety: "边界处必须认证、授权、校验输入并处理超时和错误；客户端不能保存不应暴露的服务端密钥。",
    related: ["api-key", "oauth", "rate-limit", "function-calling"]
  },
  {
    id: "oauth",
    cn: "OAuth 授权",
    en: "OAuth 2.0 Authorization Framework",
    category: "接口与安全",
    oneLine: "OAuth 让用户授权第三方应用有限访问资源，而无需把账户密码交给第三方。",
    professional: "OAuth 2.0 是委托授权框架：客户端经授权流程取得具有特定范围和期限的访问令牌，再代表资源所有者访问资源服务器；身份认证通常由 OpenID Connect 等机制补充。",
    plain: "用户给应用一张限定用途和期限的通行证，而不是把主账户密码交出去。",
    life: "像酒店给住客一张只能开本人房门、退房即失效的房卡，不是把总钥匙复制给住客。",
    engineer: "像 IAM 签发的短期受限凭据：持有者只能对指定资源执行允许动作，服务端仍需逐次验证作用域和有效期。",
    misconception: "常见误解是 OAuth 本身就是登录协议，或授权一次就能永久访问所有数据；范围、令牌寿命和撤销均受服务控制。",
    safety: "使用推荐授权流程、精确回调地址、state 与 PKCE 等防护，令牌放入安全存储并申请最小范围。",
    related: ["api", "api-key", "tool-calling", "system-prompt"]
  },
  {
    id: "api-key",
    cn: "API 密钥",
    en: "Application Programming Interface Key (API Key)",
    category: "接口与安全",
    oneLine: "API Key 是服务识别和授权调用方的秘密凭据，泄露后他人可能冒用额度与权限。",
    professional: "API Key 通常关联项目、应用或账户，由服务端在请求中校验，用于认证调用来源并施加权限、配额和计费策略；它常作为持有者凭据使用。",
    plain: "谁拿到这串秘密，往往就能以该项目身份调用服务，因此不能把它当普通编号。",
    life: "像办公室门禁卡：系统认卡并记录进出，但捡到卡的人在挂失前也可能冒用。",
    engineer: "像服务账号使用的共享秘密；它证明调用方持有凭据，却不像 OAuth 那样天然表达某个用户的委托范围。",
    misconception: "常见误解是订阅型工具提供的 Key 一定可用于生产 API；交互式工具凭据、模型 API 凭据和计费权益可能彼此独立。",
    safety: "只存于秘密管理或环境变量，不写入前端、仓库、日志和聊天；按环境分离、限制权限并支持轮换和吊销。",
    related: ["api", "oauth", "rate-limit", "tool-calling"]
  },
  {
    id: "rate-limit",
    cn: "速率限制",
    en: "Rate Limit",
    category: "接口与安全",
    oneLine: "Rate Limit 限制一定时间内允许的请求量或 Token 量，以保护容量并公平分配资源。",
    professional: "Rate Limit 可按账户、项目、模型或端点约束每秒或每分钟的请求、Token 等指标；超过限制时服务通常拒绝或延迟请求，并可能返回重试信息。",
    plain: "额度还有剩余，也可能因为短时间请求太密而被暂时拦下。",
    life: "像高速公路匝道信号灯按节奏放车，目的不是取消通行资格，而是避免车辆瞬间挤爆主路。",
    engineer: "像 API 网关的令牌桶限流：当前可通过的请求速率，和后端能承载多少并发任务不是同一指标。",
    misconception: "常见误解是速率限制等于月度配额，或提高并发一定提高吞吐；多个独立限制可能同时生效。",
    safety: "客户端应尊重服务端重试提示，采用有上限的指数退避和抖动，并避免无界重试造成费用与拥塞放大。",
    related: ["api", "api-key", "concurrency", "token"]
  },
  {
    id: "concurrency",
    cn: "并发",
    en: "Concurrency",
    category: "工程基础",
    oneLine: "Concurrency 表示同一时段内有多少任务处于进行中，不等同于每秒完成多少任务。",
    professional: "Concurrency 描述多个操作的生命周期发生重叠，可由线程、进程、事件循环或分布式请求实现；实际吞吐还受服务时间、资源争用和上游限制影响。",
    plain: "它关心同时在办的单有多少，而不是一分钟最终办完多少单。",
    life: "像超市同时开放的收银台数量；开更多台可能减少排队，也可能受收银员和补货速度限制。",
    engineer: "像工作队列允许的在途任务数：增加并行度可隐藏等待时间，但锁竞争、连接池、内存和下游容量仍会形成上限。",
    misconception: "常见误解是并发等于并行；任务可以交错并发却只在一个核心上运行，也可以真正由多核并行。",
    safety: "必须设置并发上限、超时和背压，写操作还要处理竞态、幂等性与顺序要求。",
    related: ["rate-limit", "inference", "api", "cli"]
  },
  {
    id: "ide",
    cn: "集成开发环境",
    en: "Integrated Development Environment (IDE)",
    category: "工程基础",
    oneLine: "IDE 把代码编辑、导航、构建、调试和版本控制等开发能力集成到一个环境中。",
    professional: "Integrated Development Environment 通过语言服务、项目模型、调试器和构建工具集成，为软件开发提供语义补全、诊断、重构和运行控制。",
    plain: "它是一张软件开发工作台，让写代码、找定义、看错误和调试不用频繁切换工具。",
    life: "像设备齐全的维修工位：照明、图纸、量具和测试仪都在手边，但关键判断仍由负责人完成。",
    engineer: "像把编辑器、版本控制、测试、部署和可观测工具接到同一工作台中，底层工具仍可独立运行。",
    misconception: "常见误解是 IDE 就是编译器，或安装 IDE 就自动拥有正确工具链；它常只是协调外部编译与调试组件。",
    safety: "只安装可信扩展，审查工作区任务和自动执行脚本；打开陌生项目时使用受限信任模式。",
    related: ["cli", "api", "cdp", "dom"]
  },
  {
    id: "cli",
    cn: "命令行界面",
    en: "Command-Line Interface (CLI)",
    category: "工程基础",
    oneLine: "CLI 是通过文本命令和参数操作程序的界面，适合精确复现与自动化。",
    professional: "Command-Line Interface 从终端接收命令、选项、参数和标准输入，并通过标准输出、标准错误与退出码返回结果，可被 shell 脚本或其他进程组合。",
    plain: "用户用一行文字明确告诉程序做什么，程序再用文字和状态码报告结果。",
    life: "像按固定报码向仓库窗口下单；写法严格，但同一张单容易复制、复核和重复执行。",
    engineer: "像通过云平台 CLI 输入 list、plan 与 apply 命令；它是操作界面，不等于背后的控制平面实现。",
    misconception: "常见误解是 CLI 天然比图形界面高级或安全；它只是另一种交互方式，错误命令同样可能造成破坏。",
    safety: "执行前核对工作目录、目标和参数，避免把秘密放入会被历史记录或进程列表捕获的命令行。",
    related: ["ide", "api", "concurrency", "tool-calling"]
  },
  {
    id: "dom",
    cn: "文档对象模型",
    en: "Document Object Model (DOM)",
    category: "浏览器技术",
    oneLine: "DOM 是浏览器把文档解析为可由脚本读取和修改的对象树。",
    professional: "Document Object Model 定义文档节点、属性、事件及操作接口；HTML 被解析后形成 DOM，脚本运行还可持续改变它，因此当前 DOM 不一定等于最初源码。",
    plain: "网页源码进入浏览器后变成一棵可操作的树，按钮、标题和表单都是树上的节点。",
    life: "像舞台剧本被搭成真实舞台：演出中可移动道具和新增角色，所以眼前布置未必与原始剧本完全一致。",
    engineer: "像编译器把源代码解析成可变的抽象语法树；后续遍历和变换针对树结构，而不是反复编辑原始字符。",
    misconception: "常见误解是查看页面源代码就能看到当前 DOM，或 DOM 就等于屏幕像素；样式、布局和渲染还经过其他阶段。",
    safety: "把不可信字符串写入 DOM 时使用文本接口和安全模板，避免 innerHTML 等注入路径导致跨站脚本攻击。",
    related: ["cdp", "accessibility-tree", "ide", "api"]
  },
  {
    id: "cdp",
    cn: "Chrome 开发者工具协议",
    en: "Chrome DevTools Protocol (CDP)",
    category: "浏览器技术",
    oneLine: "CDP 是检查和控制 Chromium 浏览器内部能力的调试协议。",
    professional: "Chrome DevTools Protocol 通过分域命令和事件暴露页面、网络、运行时、DOM、性能等浏览器功能，开发者工具和自动化客户端可经调试连接使用。",
    plain: "它像浏览器的后台控制通道，工具可用它查看网络、执行脚本、截屏或操纵页面。",
    life: "像剧院后台的调度台：能监听各部门状态并发出技术指令，但普通观众席并不开放这些控制。",
    engineer: "像面向特定浏览器实现的调试 API：能力深入且实现相关，不能假定另一种浏览器提供完全相同的事件与命令。",
    misconception: "常见误解是 CDP 是所有浏览器统一的网页自动化标准；它主要对应 Chromium，版本与实现差异需要处理。",
    safety: "调试端口可读取页面数据并执行高权限操作，不应暴露到不可信网络；连接已登录浏览器必须显式授权。",
    related: ["dom", "accessibility-tree", "cli", "api"]
  },
  {
    id: "accessibility-tree",
    cn: "无障碍树",
    en: "Accessibility Tree",
    category: "浏览器技术",
    oneLine: "无障碍树是浏览器向辅助技术呈现界面语义、名称、状态和关系的结构。",
    professional: "Accessibility Tree 由 DOM、ARIA、原生控件语义、样式和可见状态等信息计算而来，供屏幕阅读器和其他辅助技术通过平台无障碍 API 使用。",
    plain: "它把网页视觉界面整理成“这是什么、叫什么、现在什么状态、怎样操作”的语义目录。",
    life: "像博物馆为盲人访客制作的触觉与语音导览图，突出展品身份和行走关系，而不是复制墙面每个装饰像素。",
    engineer: "像编译器面向特定消费者生成的语义中间表示：会省略纯装饰节点，并把控件角色、标签和状态标准化。",
    misconception: "常见误解是无障碍树是 DOM 的完整副本；隐藏、装饰或缺少语义的节点可能不出现，错误 ARIA 也会造成失真。",
    safety: "优先使用原生语义元素，确保名称、键盘操作、焦点和状态可感知；自动检查不能替代屏幕阅读器与用户测试。",
    related: ["dom", "cdp", "ide", "multimodal"]
  }
];
