window.COURSE_PARTS=window.COURSE_PARTS||{}; window.COURSE_PARTS.conceptsAgent=[
  {
    id:"workflow",cn:"工作流",en:"Workflow",category:"流程与主体",
    oneLine:"工作流按预先设计的步骤和分支推进任务。",
    professional:"工作流是由固定步骤、条件分支、重试和输入输出契约组成的执行流程；路径主要由设计者预先规定。",
    plain:"先把办事顺序画好，系统照着走，遇到已知情况就走对应分支。",
    life:"像照菜谱做菜：步骤可以有“没熟就再煮两分钟”，但不是临场发明整套做法。",
    engineer:"像 CI/CD 流水线中的固定阶段：条件命中哪条规则，任务就沿预设分支执行。",
    misconception:"有条件分支或模型参与，不等于它就是 AI Agent；关键看路径是否由系统预设。",
    safety:"为每一步限定权限、超时、重试次数和失败出口，避免流程卡死或重复产生副作用。",
    related:["AI Agent","Agent Loop","Guardrail"]
  },
  {
    id:"ai-agent",cn:"AI 智能体",en:"AI Agent",category:"流程与主体",
    oneLine:"AI Agent 是在约束内围绕目标动态选择下一步行动的系统。",
    professional:"AI Agent 通常由模型、Harness、上下文、工具和状态组成；模型根据观察提出下一步行动，Harness 校验并执行，直到完成或触发停止条件。",
    plain:"它不是只回答一句话，而是会看当前结果，再决定接下来查什么、做什么或停下来。",
    life:"像受过培训的办事员：目标明确，但会根据现场材料选择下一项手续。",
    engineer:"像自动化运维控制器：根据实时状态选择动作，但仍受 IAM、资源配额和超时限制。",
    misconception:"Agent 不是一个更会聊天的模型，也不等于可以脱离权限、预算和人工责任自主运行。",
    safety:"必须设置可用工具、最小权限、费用与步数预算、停止条件，并让高风险结果由人复核。",
    related:["Workflow","Agent Loop","Harness","Tool"]
  },
  {
    id:"agent-loop",cn:"智能体循环",en:"Agent Loop",category:"循环与推理",
    oneLine:"智能体循环让系统反复观察结果、提出行动并决定继续还是停止。",
    professional:"Agent Loop 是“观察上下文—模型推理并提议行动—Harness 校验与执行—回填结果—判断停止”的迭代控制结构。",
    plain:"每做一步都看一眼结果，再决定下一步，而不是一开始把所有动作写死。",
    life:"像导航边走边重算路线，但到达、超时、超预算或风险过高时必须停止。",
    engineer:"像带熔断器的服务重试循环：每轮读取反馈，同时受最大次数、时限和故障退出条件约束。",
    misconception:"循环不是无限重试；没有预算、停止条件和失败出口的循环是不完整的。",
    safety:"明确步数、时间、Token、费用和重试预算，并设置成功、失败、人工接管和紧急停止条件。",
    related:["AI Agent","Loop Engineering","Observability"]
  },
  {
    id:"planning",cn:"规划",en:"Planning",category:"循环与推理",
    oneLine:"规划把目标拆成可执行步骤，并可随反馈调整。",
    professional:"规划是模型或系统根据目标、约束和当前状态生成任务分解、顺序、依赖与验证点的过程。",
    plain:"先想清楚要做哪几件事、先后顺序和怎样算完成，再开始动手。",
    life:"像搬家前列清单和安排车辆；发现电梯停运时还要改路线。",
    engineer:"像发布流水线把变更拆成构建、测试、部署和验收阶段，每一步都要检查结果才能继续。",
    misconception:"模型写出一份看似完整的计划，不代表计划正确、可行或必须原样执行。",
    safety:"计划涉及外部写入、付费或不可逆动作时，应在执行前校验前提并设置审批点。",
    related:["Agent Loop","Reflection/Critique","Human-in-the-loop"]
  },
  {
    id:"reflection-critique",cn:"反思与批评",en:"Reflection/Critique",category:"循环与推理",
    oneLine:"反思与批评用检查标准找出结果缺陷并指导修正。",
    professional:"Reflection/Critique 是对计划、过程或输出进行自检、同模型复核、异模型复核或规则校验，再把反馈送回循环的机制。",
    plain:"做完先对照要求挑错，再决定修改还是交付。",
    life:"像写完邮件后按收件人、附件和语气逐项复查，而不是只凭“感觉不错”。",
    engineer:"像自动化测试、静态检查与同伴评审：只有外部检查才能发现一部分错误，不能靠系统自信。",
    misconception:"让同一个模型“再想一遍”不保证纠错；它可能重复原来的盲点。",
    safety:"优先使用外部事实、明确量表和可执行测试；高风险结论仍需独立验证或人工复核。",
    related:["Planning","Evaluation/Evals","Agent Loop"]
  },
  {
    id:"memory",cn:"记忆",en:"Memory",category:"记忆与上下文",
    oneLine:"Agent 的记忆通常是外部存储、检索和上下文注入，不是模型永久记住一切。",
    professional:"Memory 是将对话、事实或任务状态写入外部存储，在需要时检索、筛选并注入模型上下文的机制；它不等同于修改模型参数。",
    plain:"先把资料记在外部笔记里，下次找到相关部分再放回模型眼前。",
    life:"像用记事本：写下来不等于一直背在脑中，使用时还要翻到正确的一页。",
    engineer:"像应用把状态写入数据库或对象存储，再按需查询到工作内存，而不是写进运行时本身。",
    misconception:"开启 Memory 不代表模型会完整、准确、永久地记住所有内容；检索可能遗漏，记录也可能过期。",
    safety:"记忆写入应有同意、范围、纠错和删除机制，敏感信息应最少保存并控制检索权限。",
    related:["Short-term Memory","Long-term Memory","Persistent Memory","Context Engineering"]
  },
  {
    id:"short-term-memory",cn:"短期记忆",en:"Short-term Memory",category:"记忆与上下文",
    oneLine:"短期记忆保存当前任务临时需要的状态和近期信息。",
    professional:"短期记忆包括当前会话上下文、工作草稿、工具结果和临时状态，通常容量有限，并随会话结束、压缩或过期而消失。",
    plain:"它是眼前这件事的工作台，只摆当前要用的材料。",
    life:"像做菜时台面上的食材和步骤卡，做完后会收走，不是永久档案。",
    engineer:"像进程缓存或临时工作区：访问快但容量有限，会话结束、过期或覆盖后内容不再可靠。",
    misconception:"短期记忆不等于整个聊天记录，也不保证长对话早期内容仍在上下文中。",
    safety:"压缩或丢弃前保留必要状态和来源；不要把只存在短期记忆的信息当成持久承诺。",
    related:["Memory","Long-term Memory","Session"]
  },
  {
    id:"long-term-memory",cn:"长期记忆",en:"Long-term Memory",category:"记忆与上下文",
    oneLine:"长期记忆把可复用信息持久保存，并在未来任务中检索注入。",
    professional:"长期记忆是跨会话保存的外部记录，可包含用户偏好、稳定事实和经验摘要，并通过搜索、排序和权限过滤进入新上下文。",
    plain:"它像长期档案，下次办类似事情时可以查出来继续用。",
    life:"像家庭通讯录：长期保存，但号码变了仍要更新，找错人也会出错。",
    engineer:"像数据库中的持久配置：服务重启后仍在，但读取时要校验版本、权限与数据新鲜度。",
    misconception:"长期保存不等于永远正确；过时、冲突和误写的记忆都会误导后续任务。",
    safety:"设置写入审批、来源、有效期、冲突处理、访问控制和可删除能力。",
    related:["Memory","Persistent Memory","Session Search"]
  },
  {
    id:"multi-agent",cn:"多智能体",en:"Multi-Agent",category:"协作与扩展",
    oneLine:"多智能体让多个 Agent 分工协作，但会增加协调成本。",
    professional:"Multi-Agent 系统把任务分配给具有不同角色、上下文或工具权限的多个 Agent，并通过消息、共享状态或调度器汇总结果。",
    plain:"把一件事分给几位数字同事，有人查资料、有人执行、有人复核。",
    life:"像项目小组：分工可能更快，但沟通、重复劳动和责任边界也会变复杂。",
    engineer:"像多个微服务通过消息队列协作：并行能扩展吞吐，却要处理竞态、重复消息和最终一致性。",
    misconception:"Agent 越多不一定越好；简单任务常被协调开销拖慢，错误也可能相互放大。",
    safety:"为每个 Agent 限定权限和预算，记录交接链，并由明确责任方验证最终结果。",
    related:["AI Agent","Subagent","Observability"]
  },
  {
    id:"subagent",cn:"子智能体",en:"Subagent",category:"协作与扩展",
    oneLine:"子智能体是由上级 Agent 委派具体子任务的受限执行实例。",
    professional:"Subagent 通常继承或获得裁剪后的目标、上下文、工具和权限，独立完成一项任务后把结果返回父 Agent。",
    plain:"主办人把一个明确的小任务交给助手，助手完成后回来汇报。",
    life:"像请同事只核对账单：任务边界清楚，最终是否采用仍由负责人决定。",
    engineer:"像任务编排器把受限工作放进队列：子任务有独立输入、权限和超时，结果回到主控制路径。",
    misconception:"子智能体不是天然更安全或更准确，也不应默认继承父 Agent 的全部秘密和权限。",
    safety:"只传必要上下文与最小权限，设置并发、费用、超时和回收规则，并验证返回结果。",
    related:["Multi-Agent","AI Agent","Sandbox"]
  },
  {
    id:"plugin",cn:"插件",en:"Plugin",category:"协作与扩展",
    oneLine:"插件是给产品安装功能的扩展包。",
    professional:"Plugin 是产品定义的可安装扩展单元，可封装代码、配置、工具、Skills、界面或外部服务集成；其格式和生命周期由宿主产品决定。",
    plain:"像给应用装扩展，让它多出一组功能。",
    life:"像给电钻换附件：扩展用途，但是否匹配、安全仍取决于接口和来源。",
    engineer:"像应用加载扩展包：插件能增加能力，也进入宿主的依赖、故障与信任边界。",
    misconception:"Plugin 不是 MCP；前者是产品扩展包，后者是连接双方的协议。",
    safety:"安装前核对来源、代码、权限和更新机制；卸载插件不一定自动撤销其外部授权。",
    related:["Model Context Protocol (MCP)","Agent Skills","Toolset"]
  },
  {
    id:"mcp",cn:"模型上下文协议",en:"Model Context Protocol (MCP)",category:"协作与扩展",
    oneLine:"MCP 是连接 AI 应用与外部能力的协议，不是授权机制。",
    professional:"MCP 规定客户端与服务器如何协商并交换工具、资源和提示等能力及其调用消息；传输可采用本地或网络方式，但身份认证、授权和沙箱需另行实现。",
    plain:"它统一双方怎样介绍和请求能力，像共同语言，不替你决定谁能做什么。",
    life:"像快递面单格式：规定信息怎么填写，却不等于门禁卡或付款许可。",
    engineer:"像服务间 API 协议：消息格式能互通，但认证、授权、秘密和运行隔离仍是独立控制。",
    misconception:"接上 MCP 不代表服务已被信任、获得授权或被安全隔离；协议本身不会自动授予权限。",
    safety:"分别配置认证、最小授权、工具白名单、传输保护和审计，并把服务器返回内容视为不可信输入。",
    related:["Plugin","Tool","Harness","Sandbox"]
  },
  {
    id:"agent-skills",cn:"智能体技能",en:"Agent Skills",category:"协作与扩展",
    oneLine:"Agent Skills 是可复用、可移植的操作说明与配套资源。",
    professional:"Agent Skills 通常以结构化说明文件组织任务步骤、约束、参考资料和脚本，并按需加载到 Agent 上下文以指导其使用现有工具。",
    plain:"它像给数字同事的一本岗位操作手册，告诉它这类事情怎样做。",
    life:"像标准食谱：指导厨师使用厨房已有器具，但食谱本身不是器具。",
    engineer:"像团队运行手册和自动化脚本：统一操作流程，却不自动获得生产账号或资源权限。",
    misconception:"Skill 不是 Tool，也不是 Plugin；它主要提供方法和知识，实际动作仍由工具和 Harness 完成。",
    safety:"把 Skill 当作可执行供应链内容审查；限制其脚本权限，并在更新后重新验证关键流程。",
    related:["Plugin","Tool","Harness"]
  },
  {
    id:"harness",cn:"智能体运行框架",en:"Harness",category:"运行时与工程",
    oneLine:"Harness 是承载模型、上下文、工具执行和循环控制的运行时。",
    professional:"Harness 负责组装消息、调用模型、解析 Tool Calling、校验权限、实际执行工具、回填结果、维护状态并实施预算与停止条件。",
    plain:"模型负责提出“想做什么”，Harness 才是检查许可并真正动手的执行系统。",
    life:"像餐厅前台与后厨调度：顾客提出要求不等于菜已做好，系统还要核单、派工和回传结果。",
    engineer:"像应用通过 API 网关调用后端：请求先经过身份、参数和策略校验，服务执行后再返回结果。",
    misconception:"Tool Calling 只是模型生成的调用提议，不是动作已经发生；真正执行者是 Harness。",
    safety:"在执行边界做参数验证、权限检查、超时、隔离、幂等保护、审计和人工审批。",
    related:["AI Agent","Tool","Agent Loop","Guardrail"]
  },
  {
    id:"harness-engineering",cn:"运行框架工程",en:"Harness Engineering",category:"运行时与工程",
    oneLine:"Harness Engineering 让 Agent 的运行时变得可控、可靠和可审计。",
    professional:"Harness Engineering 涵盖模型接入、上下文编排、工具执行、权限、状态、错误恢复、配额、日志和人机交互等运行基础设施设计。",
    plain:"它不是只调提示词，而是把 Agent 周围那套执行系统做好。",
    life:"像经营厨房：菜谱之外，还要管进货、工位、卫生、出餐和事故处理。",
    engineer:"像建设可靠的平台运行时：既要正确编排服务，也要处理超时、重试、权限、错误码和回滚。",
    misconception:"换一个更强模型不能替代 Harness Engineering；许多可靠性和安全问题发生在模型之外。",
    safety:"优先把权限检查、资源上限和审计放在模型无法绕过的执行层。",
    related:["Harness","Loop Engineering","Context Engineering","Observability"]
  },
  {
    id:"loop-engineering",cn:"循环工程",en:"Loop Engineering",category:"运行时与工程",
    oneLine:"Loop Engineering 设计 Agent 每轮如何推进、验证、重试和停止。",
    professional:"Loop Engineering 定义观察、决策、行动、反馈的循环策略，以及步数、时间、费用预算、重试退避、检查点和终止判定。",
    plain:"它规定每一步做完看什么、失败几次就停、什么时候请人接手。",
    life:"像登山设定折返点：不仅规划向上走，也规定天气恶化或时间不足时撤退。",
    engineer:"像状态机与熔断器组合：每轮只能合法转移，超时、预算耗尽或异常就进入安全停止态。",
    misconception:"让 Agent 一直循环到“自己满意”不是可靠策略；Loop 必须有明确预算和停止条件。",
    safety:"限制最大轮数、墙钟时间、Token、费用和副作用次数，并保留紧急中止与人工接管。",
    related:["Agent Loop","Harness Engineering","Evaluation/Evals"]
  },
  {
    id:"context-engineering",cn:"上下文工程",en:"Context Engineering",category:"记忆与上下文",
    oneLine:"上下文工程把当前任务真正需要的信息组织进模型输入。",
    professional:"Context Engineering 负责选择、检索、排序、压缩和标注系统指令、历史、记忆、工具结果与外部证据，使有限上下文服务于当前决策。",
    plain:"不是把所有资料一股脑塞进去，而是把正确内容在正确时机摆到模型面前。",
    life:"像开会前准备资料包：只放相关版本，并把决定事项和参考材料分清。",
    engineer:"像为受限查询窗口组织数据：选择必要记录、标明来源与版本，避免噪声和过期数据污染。",
    misconception:"上下文越长不一定越好；噪声、冲突和位置效应都可能降低可靠性。",
    safety:"区分可信指令与不可信数据，保留来源，过滤秘密，并防止检索内容覆盖高优先级规则。",
    related:["Memory","Harness Engineering","Prompt Injection"]
  },
  {
    id:"sandbox",cn:"沙箱",en:"Sandbox",category:"安全与质量",
    oneLine:"沙箱用隔离边界限制代码和工具能触及的资源。",
    professional:"Sandbox 通过进程、容器、虚拟机、文件系统、网络或系统调用策略约束执行环境，降低不可信操作影响宿主与数据的范围。",
    plain:"把操作放进围栏里，即使出错也尽量只影响指定区域。",
    life:"像让孩子在铺好防护垫的区域做实验，危险会减少但不会自动归零。",
    engineer:"像工作负载运行在受限容器或虚拟机中：越权访问被阻断，但平台漏洞或错误挂载仍可能穿透边界。",
    misconception:"沙箱不是绝对安全，也不等于授权；能在沙箱运行不代表允许访问其中所有资源。",
    safety:"采用最小挂载、默认断网或网络白名单、资源上限和短生命周期，并及时更新隔离层。",
    related:["Guardrail","Harness","Model Context Protocol (MCP)"]
  },
  {
    id:"guardrail",cn:"防护规则",en:"Guardrail",category:"安全与质量",
    oneLine:"Guardrail 用规则和控制把 Agent 行为限制在可接受范围。",
    professional:"Guardrail 是执行前、执行中和执行后的政策检查与技术控制，包括输入过滤、权限限制、参数约束、审批、输出验证和阻断。",
    plain:"它像道路护栏和交通规则，降低偏离目标后造成严重后果的概率。",
    life:"像银行卡的单笔限额与异常交易确认：不替你判断所有事情，但能拦住部分高风险动作。",
    engineer:"像 IAM 策略加熔断规则：既限制允许的操作，也在异常状态下阻断或升级处理。",
    misconception:"Guardrail 不能保证模型永不出错，也不能只靠一条提示词实现。",
    safety:"关键控制应在 Harness 或基础设施层强制执行，并持续测试绕过路径和误拦截。",
    related:["Sandbox","Human-in-the-loop","Prompt Injection"]
  },
  {
    id:"human-in-the-loop",cn:"人在回路中",en:"Human-in-the-loop",category:"安全与质量",
    oneLine:"人在回路中让人类在关键节点审核、批准、纠正或接管。",
    professional:"Human-in-the-loop 在 Agent 流程中设置人工输入、审批、复核和升级机制，尤其用于高风险、不确定或不可逆决策。",
    plain:"系统可以先准备，但到关键一步要由人确认，必要时人直接接手。",
    life:"像网银转账最后要本人核对收款方和金额。",
    engineer:"像生产发布先跑 CI 测试，再由值班负责人批准部署；健康检查异常时回滚到已知版本。",
    misconception:"有人点“批准”不等于有效监督；审批者必须看到足够上下文并有真实拒绝权。",
    safety:"明确哪些动作必须审批，展示影响和证据，防止疲劳点击，并保留撤销或回滚路径。",
    related:["Guardrail","Observability","Evaluation/Evals"]
  },
  {
    id:"observability",cn:"可观测性",en:"Observability",category:"安全与质量",
    oneLine:"可观测性让人能从记录和指标还原 Agent 做了什么以及为什么失败。",
    professional:"Observability 通过结构化日志、调用轨迹、指标、成本、状态变化和审计事件，支持监控、调试、归因与告警。",
    plain:"不仅知道任务失败，还能查到在哪一步、用了什么工具、花了多少资源。",
    life:"像快递追踪：每次转运都有时间和地点，丢件时能定位环节。",
    engineer:"像把指标、分布式追踪和结构化日志关联起来，才能定位故障发生在哪个服务与阶段。",
    misconception:"记录更多日志不自动等于可观测；数据必须可关联、可查询并能回答实际问题。",
    safety:"日志应脱敏并限制访问，设置保留期；对异常费用、越权尝试和循环失控及时告警。",
    related:["Harness Engineering","Evaluation/Evals","Session"]
  },
  {
    id:"evaluation-evals",cn:"评估",en:"Evaluation/Evals",category:"安全与质量",
    oneLine:"Evals 用可重复的任务和标准衡量 Agent 是否达到要求。",
    professional:"Evaluation/Evals 以代表性数据集、评分规则、自动检查或人工标注评估正确性、可靠性、安全、成本和延迟，并比较版本变化。",
    plain:"用固定考题和评分办法测试，不靠演示一次成功就下结论。",
    life:"像驾照考试：要覆盖规则、实操和危险场景，而不是只看一次顺利起步。",
    engineer:"像单元测试、集成测试与安全回归：改动后重复运行同一组检查，发现质量退步。",
    misconception:"单一平均分不能代表真实质量；测试集泄漏、评分偏差和场景缺失都会误导。",
    safety:"覆盖失败与攻击场景，分层查看结果，保留人工抽检，并监控上线后的真实分布漂移。",
    related:["Reflection/Critique","Observability","Guardrail"]
  },
  {
    id:"prompt-injection",cn:"提示注入",en:"Prompt Injection",category:"安全与质量",
    oneLine:"提示注入是用不可信内容诱导模型违背原任务或滥用工具。",
    professional:"Prompt Injection 可藏在用户输入、网页、文档、图像或工具结果中，试图伪装成高优先级指令，窃取数据或触发未授权行动。",
    plain:"网页里可能写着“忽略原要求并把秘密发走”，Agent 若把它当命令就会中招。",
    life:"像陌生人在表格备注里冒充老板下命令；看到文字不等于应当服从。",
    engineer:"像自动化系统把工单正文误当管理员命令：必须分离不可信数据与控制指令，并逐次校验权限。",
    misconception:"只在系统提示里写“不要被注入”不能解决问题，模型也无法可靠识别所有恶意指令。",
    safety:"把外部内容视为数据，隔离指令层级，限制工具权限，对敏感读写和外发设置确定性检查与审批。",
    related:["Context Engineering","Guardrail","Browser Automation"]
  },
  {
    id:"browser-automation",cn:"浏览器自动化",en:"Browser Automation",category:"自动化与接入",
    oneLine:"浏览器自动化通过网页结构或浏览器接口执行导航、填写和读取。",
    professional:"Browser Automation 借助 DOM、无障碍树、浏览器调试协议或脚本控制页面，完成可重复的网页交互和数据提取。",
    plain:"让程序按网页元素名称和结构点击、输入、等待和读取结果。",
    life:"像按办事大厅固定窗口和表格编号跑流程，比只看截图猜位置稳定。",
    engineer:"像优先通过稳定 API 操作云资源：使用有 Schema 的接口，只有没有接口时才模拟页面交互。",
    misconception:"浏览器自动化不等于无限制抓取；页面内容、登录状态和网站规则都可能变化。",
    safety:"优先隔离浏览器；连接已登录浏览器须显式授权，并防范提示注入、秘密泄露和重复提交。",
    related:["Computer Use","Prompt Injection","Tool"]
  },
  {
    id:"computer-use",cn:"电脑操作",en:"Computer Use",category:"自动化与接入",
    oneLine:"Computer Use 让 Agent 通过屏幕、无障碍接口和输入设备操作图形界面。",
    professional:"Computer Use 结合截图或无障碍树感知界面，并通过鼠标、键盘或系统自动化接口执行动作，适合缺少结构化 API 的桌面任务。",
    plain:"Agent 像人一样看屏幕、移动鼠标和敲键盘，但速度和判断都可能受界面变化影响。",
    life:"像远程指导别人操作电脑：按钮挪位、弹窗遮挡或看错字都会让步骤偏离。",
    engineer:"像没有 API 时用桌面自动化操作旧系统：能工作，但比结构化接口脆弱且更难验证状态。",
    misconception:"Computer Use 不是可靠 API，也不会自动获得操作系统权限；看得到界面不代表能控制管理员窗口。",
    safety:"在交互式桌面会话中授予最小系统权限，对密码、付款、删除和管理员动作设置阻断或人工确认。",
    related:["Browser Automation","Computer Vision","Human-in-the-loop"]
  },
  {
    id:"webhook",cn:"网络回调",en:"Webhook",category:"自动化与接入",
    oneLine:"Webhook 在事件发生时由服务向指定地址发送 HTTP 通知。",
    professional:"Webhook 是事件驱动的服务器到服务器回调，发送方通常以 HTTP 请求传递事件载荷，接收方负责认证、去重、快速响应和后续处理。",
    plain:"不是你反复去问“有新消息吗”，而是有事时对方主动通知你。",
    life:"像快递到站短信：事件发生就推送通知，但短信重复时不能重复领件。",
    engineer:"像事件队列推送而非定时轮询：处理器要快速确认，并用事件编号避免同一消息被处理两次。",
    misconception:"Webhook 通常是至少送达而非恰好一次，超时重试可能产生重复事件。",
    safety:"验证签名和时间戳，限制来源与载荷大小，使用幂等键，并把耗时工作移到队列。",
    related:["Cron","Gateway","Tool"]
  },
  {
    id:"cron",cn:"定时任务",en:"Cron",category:"自动化与接入",
    oneLine:"Cron 按时间表达式触发任务，不保证任务成功完成。",
    professional:"Cron 是基于日历时间调度命令或作业的机制，负责触发时机；执行结果、重试、并发和告警需由任务系统处理。",
    plain:"像闹钟到点响，提醒开始做事，但不代表事情已经办完。",
    life:"像每天七点的服药提醒：响铃可能重复或错过，仍要确认是否真的服用。",
    engineer:"像调度器按时投递批处理作业：触发只是入口，退出码、并发控制和故障恢复仍需单独设计。",
    misconception:"Cron 不保证精确实时、只运行一次或执行成功；时区和夏令时也会影响计划。",
    safety:"明确时区，防止任务重叠，设置超时、幂等、失败告警和补跑策略。",
    related:["Webhook","Observability","Agent Loop"]
  },
  {
    id:"gateway",cn:"网关",en:"Gateway",category:"自动化与接入",
    oneLine:"Gateway 是请求进入多个模型、工具或服务前的统一入口。",
    professional:"Gateway 在入口层提供路由、认证、限流、协议转换、策略和观测，并把请求转发到合适的后端。",
    plain:"所有请求先到总服务台，再按规则分给对应窗口。",
    life:"像园区门卫和导览台：查证、登记、分流，但不代替楼内每个房间的权限。",
    engineer:"像 API 网关：统一路由、认证和限流，却不能保证下游服务本身正确或安全。",
    misconception:"通过 Gateway 不代表已经获得所有后端权限，也不意味着网关能修复后端错误。",
    safety:"采用端到端最小授权、限流、超时和审计；避免网关日志记录明文秘密。",
    related:["Profile","Toolset","Observability"]
  },
  {
    id:"profile",cn:"配置档案",en:"Profile",category:"运行配置",
    oneLine:"Profile 是一组可切换的命名配置。",
    professional:"Profile 将模型、端点、凭据引用、工具权限、环境和行为选项组合成命名配置，便于不同任务或环境复用。",
    plain:"像保存“工作”“个人”“测试”三套设置，需要时整套切换。",
    life:"像汽车驾驶模式：一键换一组参数，但驾驶者身份和道路许可仍是另一回事。",
    engineer:"像基础设施即代码的环境配置：成组切换端点、权限和参数，变更前应校验并保留回滚版本。",
    misconception:"Profile 不是用户身份，也不会自动隔离凭据、会话或权限。",
    safety:"敏感值只引用秘密存储；切换时清楚展示目标环境和权限，并支持验证与回滚。",
    related:["Gateway","Toolset","Session"]
  },
  {
    id:"tool",cn:"工具",en:"Tool",category:"工具与会话",
    oneLine:"Tool 是 Harness 可以代表 Agent 调用的一项具体能力。",
    professional:"Tool 以名称、用途和参数模式向模型描述可用动作；模型通过 Tool Calling 提出调用请求，Harness 校验后实际执行并返回结果。",
    plain:"模型可以填写一张“请调用这个功能”的申请单，真正按下按钮的是 Harness。",
    life:"像医生开检查单：提出检查不等于检查已经完成，还要由设备和人员执行并返回报告。",
    engineer:"像客户端提交服务请求：调用方只提出动作，运行时检查 Schema、权限和策略后才执行。",
    misconception:"Tool Calling 只是模型提议，不是模型亲自执行，也不证明调用已经成功。",
    safety:"校验参数和权限，限制副作用，设置超时与幂等，并把工具返回值作为不可信输入处理。",
    related:["Toolset","Harness","Model Context Protocol (MCP)"]
  },
  {
    id:"toolset",cn:"工具集",en:"Toolset",category:"工具与会话",
    oneLine:"Toolset 是按任务或权限组合的一组工具。",
    professional:"Toolset 把多个 Tool 按领域、角色或安全边界组织起来，供 Harness 在特定会话中向模型暴露。",
    plain:"像一个工具箱，里面只放当前工作允许使用的工具。",
    life:"像维修工出门前选工具包：带得太少做不了事，带得太多会增加误用风险。",
    engineer:"像按职责划分的 API 集合：只暴露必要操作，接口越大越难授权、审计和测试。",
    misconception:"工具越多不一定能力越强；过大的 Toolset 会增加选择错误、上下文占用和攻击面。",
    safety:"按任务最小化暴露工具，分离只读与写入能力，并对高风险工具单独审批。",
    related:["Tool","Plugin","Profile"]
  },
  {
    id:"session",cn:"会话",en:"Session",category:"工具与会话",
    oneLine:"Session 是一次连续交互及其状态的边界。",
    professional:"Session 保存一段交互中的消息、工具调用、临时状态和上下文标识，可被恢复或压缩，但通常不自动等同于长期记忆。",
    plain:"它像一次办事窗口的受理单，记录这次事情的来龙去脉。",
    life:"像一次门诊记录：本次过程在同一档案里，但下次是否调阅由系统规则决定。",
    engineer:"像一次独立的应用会话：有自己的状态和资源句柄，结束后只有显式持久化的数据会留下。",
    misconception:"新建 Session 不一定删除旧数据；恢复 Session 也不代表所有历史都能塞回模型上下文。",
    safety:"设置访问控制、保留期和导出删除能力，避免跨用户混用会话或把秘密长期留在记录中。",
    related:["Short-term Memory","Session Search","Persistent Memory"]
  },
  {
    id:"session-search",cn:"会话搜索",en:"Session Search",category:"记忆与上下文",
    oneLine:"Session Search 从历史会话记录中查找与当前问题相关的片段。",
    professional:"Session Search 对已保存的对话和工具轨迹建立关键词或语义索引，按查询检索历史片段，再供人查看或注入当前上下文。",
    plain:"它是在旧聊天档案里搜索，而不是要求模型凭空回忆。",
    life:"像在邮件里搜关键词找到旧讨论，再打开相关段落核对。",
    engineer:"像在集中日志平台中检索错误码：找到候选记录后仍要核对时间、服务版本和上下文。",
    misconception:"能搜索历史不等于所有历史都属于 Persistent Memory，也不保证首条结果正确。",
    safety:"搜索结果应遵守原会话权限，显示来源与时间，并避免把其他用户或过期内容注入当前任务。",
    related:["Session","Memory","Persistent Memory"]
  },
  {
    id:"persistent-memory",cn:"持久记忆",en:"Persistent Memory",category:"记忆与上下文",
    oneLine:"Persistent Memory 是重启和跨会话后仍保留的外部记忆。",
    professional:"Persistent Memory 将选定事实、偏好或经验写入数据库、文件或索引，并在未来通过检索和上下文注入重新使用。",
    plain:"它是明确存进长期档案、以后还能查到的内容。",
    life:"像把常用地址存进通讯录；保存后会一直在，直到更新或删除。",
    engineer:"像把服务配置写入版本化数据库：重启后可恢复，但需权限控制、迁移校验和回滚。",
    misconception:"Persistent Memory 仍不是模型参数中的永久知识，也不应默认保存每一句对话。",
    safety:"仅保存必要内容，记录来源和更新时间，提供写入审批、纠错、导出、删除及加密访问控制。",
    related:["Memory","Long-term Memory","Session Search"]
  },
  {
    id:"computer-vision",cn:"计算机视觉",en:"Computer Vision",category:"感知",
    oneLine:"计算机视觉让系统从图像或视频中识别、定位和解释信息。",
    professional:"Computer Vision 使用视觉模型处理像素，完成分类、检测、分割、文字识别、场景理解或视觉问答，并输出带不确定性的结果。",
    plain:"它让机器从画面中找物体、读文字和理解大致场景。",
    life:"像隔着照片判断桌上有什么：能看出很多信息，也可能因模糊、遮挡或角度而看错。",
    engineer:"像 OCR 服务处理上传图像：输入质量、分辨率、压缩和数据分布都会影响结构化结果。",
    misconception:"视觉模型不是摄像头，也不是精确测量仪；看懂画面不代表能安全操作界面。",
    safety:"对隐私图像取得授权并最少保存；关键识别结果应结合置信度、结构化数据或人工复核。",
    related:["Computer Use","Evaluation/Evals","Human-in-the-loop"]
  }
];
