window.COURSE_PARTS=window.COURSE_PARTS||{}; window.COURSE_PARTS.conceptsFoundation=[
  {
    id: "generative-ai",
    cn: "Generative AI",
    en: "Generative Artificial Intelligence (Generative AI)",
    category: "Models and Generation",
    oneLine: "Generative AI creates new content from patterns learned in data rather than retrieving an answer verbatim from a repository.",
    professional: "Generative AI refers to AI systems that learn data distributions and generate text, images, audio, video, code, or other content in response to conditional input; their outputs are probabilistic generations.",
    plain: "It learns ways of expressing things from many examples, then composes content for the current request, but it does not guarantee that every statement is true.",
    life: "It is like a chef who understands many recipes and creates a new dish from the available ingredients instead of taking a prepared meal from the refrigerator.",
    engineer: "It is like generating a candidate production configuration from patterns in historical changes; schema validation, automated tests, change approval, and post-deployment verification are still required.",
    misconception: "A common misconception is that it copies a particular training record, or that fluent output must be correct. Generation, memorization, and fact-checking are three different things.",
    safety: "Do not treat generated content as established fact, an authorization decision, or executable code. For privacy, copyright, and high-risk operations, verify sources and require human review.",
    related: ["foundation-model", "large-language-model", "hallucination", "multimodal"]
  },
  {
    id: "foundation-model",
    cn: "Foundation Model",
    en: "Foundation Model",
    category: "Models and Generation",
    oneLine: "A foundation model is pretrained on broad data and can be adapted to many downstream tasks.",
    professional: "A foundation model gains transferable capabilities through large-scale pretraining, then serves different tasks through prompting, retrieval, fine-tuning, or tool integration; language models are only one form of foundation model.",
    plain: "It first develops a broad base of capabilities, then uses instructions, reference material, or specialized training to perform a particular job.",
    life: "It is like a student who completes a general education and can later train for work in law, customer service, or design rather than learning only one trade from the start.",
    engineer: "It is like a reusable platform service: the same core can serve multiple business systems and deployment environments through APIs, configuration, and adapters.",
    misconception: "A common misconception is that a foundation model is the same as a chat product. A chat product also includes an interface, prompting strategy, retrieval, tools, safety controls, and operational services.",
    safety: "General capabilities also create general risks. Before deployment, assess data provenance, bias, permissions, cost, and failure modes for the specific use case.",
    related: ["generative-ai", "large-language-model", "fine-tuning", "prompt"]
  },
  {
    id: "large-language-model",
    cn: "Large Language Model",
    en: "Large Language Model (LLM)",
    category: "Models and Generation",
    oneLine: "A large language model is trained on extensive language data and models Token sequences to process and generate language.",
    professional: "A large language model is a language model with substantial parameter and training-data scale. It typically learns conditional probabilities over Token sequences and gains capabilities such as question answering, writing, and coding through pretraining and subsequent alignment.",
    plain: "It excels at continuing from the available context with suitable content. Complex capabilities emerge from the training objective and scale, but the model is not a human-like database.",
    life: "It is like an improvisational writing partner who has read a vast amount of material and can continue naturally from context, yet may state hazy details with great fluency.",
    engineer: "It is like a very large probabilistic sequence-prediction service: given a Token stream, it returns a distribution over subsequent Tokens, without hard guarantees from a programming language type system or database constraints.",
    misconception: "A common misconception is that LLMs represent all of AI, or that more parameters necessarily mean greater reliability. Architecture, data, training, inference strategy, and evaluation are equally important.",
    safety: "Do not judge trustworthiness by tone. Whether sensitive data may be submitted, whether output may be executed, and how costs are calculated must be confirmed against service terms and actual testing.",
    related: ["foundation-model", "token", "transformer", "context-window"]
  },
  {
    id: "transformer",
    cn: "Transformer Architecture",
    en: "Transformer",
    category: "Model Architecture",
    oneLine: "The Transformer uses attention mechanisms to model relationships among sequence elements and is the core architecture of many modern large models.",
    professional: "The Transformer processes sequences with components such as self-attention, feed-forward networks, residual connections, and positional representations, allowing a model to aggregate information from different positions according to the task while supporting parallel training.",
    plain: "When processing a sentence, each segment can attend to other segments as needed and determine which context is most relevant to the current interpretation.",
    life: "It is like everyone at a roundtable reading all the notes but focusing on the few that matter most to their own topic.",
    engineer: "It is like analyzing a dependency graph: the current node can follow relationships to distant definitions, calls, and state instead of reading only the immediately preceding character.",
    misconception: "A common misconception is that a Transformer is an LLM. It is an architecture that can be used for different modalities and does not have to operate at large-language-model scale.",
    safety: "Attention weights are not reliable explanations or causal evidence. The model remains constrained by context length, training data, and compute resources.",
    related: ["large-language-model", "token", "context-window", "multimodal"]
  },
  {
    id: "token",
    cn: "Token",
    en: "Token",
    category: "Input and Control",
    oneLine: "A Token is a basic unit into which a model divides and processes input and output; it is not necessarily one character or one English word.",
    professional: "A Token is a sequence unit produced when a tokenizer encodes text as discrete identifiers. It may correspond to a character, part of a word, punctuation, whitespace, or a byte fragment; billing and context limits are often measured in Tokens.",
    plain: "The model first divides text into small pieces recognized by its vocabulary, then converts those pieces into identifiers for processing.",
    life: "It is like packing items into boxes under a shipping rule: one word may fit in one box or be divided among several boxes.",
    engineer: "It resembles a lexical unit in a parser, but its boundaries are determined by the model vocabulary and may not follow natural-language words, program identifiers, or data fields.",
    misconception: "A common misconception is that character count converts exactly to Token count. Different models, languages, whitespace, and encodings produce different tokenization.",
    safety: "Use the target model's official tokenizer or API usage fields for budgeting and truncation decisions rather than relying on a fixed character-to-Token ratio.",
    related: ["large-language-model", "context-window", "rate-limit", "inference"]
  },
  {
    id: "context-window",
    cn: "Context Window",
    en: "Context Window",
    category: "Input and Control",
    oneLine: "The context window is the Token-capacity boundary that a model can include in a single inference operation.",
    professional: "The context window limits the Tokens occupied by system instructions, conversation history, retrieved material, tool results, and generated content in one request. The model interface defines how input and output share that allowance.",
    plain: "Only material placed in the current window can be referenced directly for this response. Content beyond the limit must be removed, compressed, or retrieved separately.",
    life: "It is like a desk with limited space: no matter how large the archive is, only so many documents can be spread out and compared at once.",
    engineer: "It is like a memory-constrained query workspace: object storage may retain enormous logs, but one analysis can process only the portion loaded into its current working set.",
    misconception: "A common misconception is that a long context provides reliable long-term memory. Fitting material into the window does not mean the model will consistently find it, interpret it correctly, or retain it permanently.",
    safety: "Irrelevant content increases cost and dilutes important information. State critical constraints clearly, place them near the task, and test that they were not truncated.",
    related: ["token", "prompt", "system-prompt", "retrieval-augmented-generation"]
  },
  {
    id: "prompt",
    cn: "Prompt",
    en: "Prompt",
    category: "Input and Control",
    oneLine: "A Prompt combines task instructions, background, data, and output constraints provided to a model.",
    professional: "A Prompt is conditional input placed in the inference context. It may include goals, roles, examples, evidence, tool descriptions, and formatting requirements to influence the output distribution without changing model weights.",
    plain: "It is a work brief for the model: what to do, what to base the work on, and what standard the result must meet.",
    life: "It is like a renovation work order. Saying only 'make it look good' produces a very different result from specifying dimensions, materials, and acceptance criteria.",
    engineer: "It is like submitting an API request: the clearer the action, parameters, preconditions, and expected response, the less ambiguity the service must resolve.",
    misconception: "A common misconception is that a magical prompt works for every model and task. Reliable results depend on the model, context, data, and evaluation.",
    safety: "Treat external text and user input as untrusted data. Placing content in a Prompt does not give it authority to issue instructions.",
    related: ["system-prompt", "context-window", "temperature", "prompt-injection"]
  },
  {
    id: "system-prompt",
    cn: "System Prompt",
    en: "System Prompt",
    category: "Input and Control",
    oneLine: "A System Prompt is set by the application at a high-priority position in a conversation to define the model's role, rules, and boundaries.",
    professional: "A System Prompt is a high-priority instruction supplied by a service or application within the message hierarchy to establish persistent task constraints and behavior policies. It remains part of the context and is not an enforced access-control mechanism.",
    plain: "It is like a set of general rules the application gives the model in the background before users submit specific tasks.",
    life: "It is like internal duty rules for venue staff: they take priority over a visitor's temporary request, but real access control still depends on locks and permission systems.",
    engineer: "It is like policy configuration loaded when an application starts: it provides default process constraints but cannot replace IAM, network policies, or server-side parameter validation.",
    misconception: "A common misconception is that a System Prompt can never be exposed, overridden, or bypassed. Natural-language constraints do not form a complete security boundary.",
    safety: "Never put secrets in a System Prompt. Enforce high-risk restrictions with permission isolation, parameter validation, sandboxes, and human approval as well.",
    related: ["prompt", "context-window", "function-calling", "tool-calling"]
  },
  {
    id: "temperature",
    cn: "Temperature",
    en: "Temperature",
    category: "Input and Control",
    oneLine: "Temperature adjusts how concentrated the sampling distribution is, affecting output diversity but not intelligence or factual confidence.",
    professional: "Temperature commonly changes the relative probabilities of candidate Tokens by scaling generation logits: lower values concentrate sampling, while higher values flatten the distribution. Supported ranges and exact behavior depend on the model interface.",
    plain: "It controls whether the model chooses conservatively among a few high-probability expressions or more readily tries lower-probability alternatives.",
    life: "It is like adjusting exploration in music shuffle: a low setting repeats familiar hits, while a high setting surfaces more obscure tracks, but neither makes the audio system understand music better.",
    engineer: "It is like changing how broadly a load balancer explores candidate backends, not improving data quality; the input state and candidate set do not become true as a result.",
    misconception: "A common misconception is that a temperature of zero guarantees exact reproducibility, or that higher temperature is both more creative and more intelligent. Service implementation and other sampling factors can still affect results.",
    safety: "Structured, compliance-sensitive, or factual tasks usually require more controlled sampling together with validation. Do not use Temperature as a substitute for evaluation.",
    related: ["token", "inference", "hallucination", "prompt"]
  },
  {
    id: "hallucination",
    cn: "Hallucination",
    en: "Hallucination",
    category: "Model Reliability",
    oneLine: "A Hallucination is model-generated content that appears plausible but lacks support or contradicts the facts.",
    professional: "Hallucination describes output that conflicts with supplied evidence, verifiable facts, or task constraints. Common forms include fabricated sources, incorrect attribution, invented data, and unsupported inference.",
    plain: "When the model does not know, it may continue completing the sentence and use fluent language to conceal the information gap.",
    life: "It is like a passerby who is unwilling to say 'I don't know' and confidently points toward a shop that does not exist.",
    engineer: "It is like a monitoring dashboard that never queries the real metrics but assembles correctly formatted values from stale cache data; valid JSON does not mean a real observation.",
    misconception: "A common misconception is that only absurd answers count as Hallucinations. A wrong date, fabricated citation, or unsupported detail is also a Hallucination.",
    safety: "Check critical facts against authoritative sources, and ensure citations lead back to the original material. High-risk output requires independent validation and confirmation by an accountable person.",
    related: ["generative-ai", "retrieval-augmented-generation", "reasoning-model", "evaluation"]
  },
  {
    id: "multimodal",
    cn: "Multimodal",
    en: "Multimodal",
    category: "Models and Generation",
    oneLine: "A Multimodal system can process or generate multiple forms of information, such as text, images, audio, and video, within the same task.",
    professional: "A Multimodal model connects modalities through modality-specific encoders, shared representations, or cross-modal attention. It may accept one or more modalities and produce one or more modalities.",
    plain: "It can do more than read text: it may see images, hear audio, or generate visuals and combine that information in its response.",
    life: "It is like a claims examiner who reviews accident photos, listens to recordings, and reads forms together to determine whether more evidence is needed.",
    engineer: "It is like an observability platform ingesting logs, metrics, and traces through their respective collectors, normalizing them, and then performing a combined diagnosis.",
    misconception: "A common misconception is that accepting image input guarantees accurate recognition of every detail. Resolution, compression, sampling, and modality alignment all cause information loss.",
    safety: "Images and audio can also contain private data, malicious instructions, or fabricated content. Verify provenance, minimize collection, and evaluate each modality separately.",
    related: ["foundation-model", "transformer", "embedding", "context-window"]
  },
  {
    id: "embedding",
    cn: "Embedding",
    en: "Embedding",
    category: "Retrieval and Knowledge",
    oneLine: "An Embedding maps content to a vector so that content with similar meaning or features lies closer together in vector space.",
    professional: "An Embedding is a dense numerical representation produced by a model that encodes task-relevant features of text, images, or other objects and can be compared using cosine similarity, dot product, or distance functions.",
    plain: "It assigns coordinates to each piece of content so a machine can find neighbors by similarity of meaning.",
    life: "It is like placing books on a topic map: baking books sit near desserts, and cybersecurity books sit near cryptography, instead of everything being sorted only by title.",
    engineer: "It is like extracting multidimensional features from audit events for anomaly detection; it is neither the original record nor encryption or access control.",
    misconception: "A common misconception is that a vector stores fully recoverable source text, or that proximity proves two items state the same facts. It expresses only the similar features learned by the model.",
    safety: "Embeddings can still expose sensitive characteristics. Control access to both source content and vectors, and evaluate retrieval bias on representative data.",
    related: ["vector-database", "retrieval-augmented-generation", "multimodal", "token"]
  },
  {
    id: "vector-database",
    cn: "Vector Database",
    en: "Vector Database",
    category: "Retrieval and Knowledge",
    oneLine: "A Vector Database stores and indexes vectors and uses similarity search to find content closest to a query.",
    professional: "A Vector Database provides nearest-neighbor retrieval over high-dimensional vectors and commonly combines source-document references, metadata filters, access control, and index maintenance to supply candidates for semantic search or RAG.",
    plain: "Instead of finding only exact keyword matches, it prioritizes entries with similar meaning.",
    life: "It is like a warehouse that can find the most similar products by purpose, material, and style instead of retrieving items only by product number.",
    engineer: "It is like building a search index over a large document store to narrow the candidate set, except matching uses vector distance, and an approximate index can still miss the best item.",
    misconception: "A common misconception is that a Vector Database understands knowledge and answers questions on its own. It stores and retrieves content; a downstream system must still generate or organize the answer.",
    safety: "Include tenant and document permissions in filters, define deletion and index-rebuild processes, and evaluate recall, latency, and cost with real queries.",
    related: ["embedding", "retrieval-augmented-generation", "api", "context-window"]
  },
  {
    id: "retrieval-augmented-generation",
    cn: "Retrieval-Augmented Generation",
    en: "Retrieval-Augmented Generation (RAG)",
    category: "Retrieval and Knowledge",
    oneLine: "RAG retrieves external material and places relevant evidence in the context before answering instead of retraining the model.",
    professional: "Retrieval-Augmented Generation connects query transformation, retrieval, ranking, context assembly, and generation so the model can answer from external knowledge at inference time and provide traceable citations.",
    plain: "It has the model look up information before answering. The sources can be updated, but retrieving, omitting, or interpreting material incorrectly can still produce errors.",
    life: "It is like an open-book exam: you find the relevant section in the permitted material and compose an answer from it instead of retaking an entire semester of lessons just before the exam.",
    engineer: "It is like an incident-response system retrieving the runbook for the relevant service version from a knowledge base before diagnosis, then passing the relevant sections into the analysis workflow instead of retraining the system.",
    misconception: "A common misconception is that RAG changes model weights or completely eliminates Hallucinations. It only supplies evidence for the current inference operation.",
    safety: "Retrieval sources need permission filtering, versioning, and citations. Treat external documents as untrusted input, defend against Prompt Injection, and allow the model to answer that evidence is insufficient.",
    related: ["embedding", "vector-database", "context-window", "hallucination"]
  },
  {
    id: "fine-tuning",
    cn: "Fine-tuning",
    en: "Fine-tuning",
    category: "Model Adaptation and Runtime",
    oneLine: "Fine-tuning continues training a model on specific data and updates its weights to better suit a target behavior or task.",
    professional: "Fine-tuning further optimizes some or all parameters of a pretrained model with supervised examples, preference data, or parameter-efficient methods to adjust output style, format, domain behavior, or task performance.",
    plain: "Instead of showing the model a temporary instruction, it uses sets of examples to change how the model handles similar tasks in the future.",
    life: "It is like receiving feedback-driven job training after a general education: corrections become stable habits rather than a note read before every shift.",
    engineer: "It is like rebuilding a specialized model artifact with domain examples; changes are stored in the weights, while loading configuration or documents at runtime is closer to Prompting or RAG.",
    misconception: "A common misconception is that adding a few new facts calls for Fine-tuning. Knowledge that changes frequently or requires citations is usually better handled through retrieval.",
    safety: "Training data requires authorization, de-identification, and quality review. Evaluate overfitting, forgetting, bias, deployment cost, and rollback options.",
    related: ["foundation-model", "prompt", "retrieval-augmented-generation", "inference"]
  },
  {
    id: "inference",
    cn: "Inference",
    en: "Inference",
    category: "Model Adaptation and Runtime",
    oneLine: "Inference is the runtime phase in which a trained model processes new input and produces a prediction or generated result.",
    professional: "Inference encodes input, runs the model's forward computation, and produces output according to a decoding strategy. Latency, throughput, accelerator memory, context length, and sampling parameters jointly affect service performance and cost.",
    plain: "Training develops the capability; Inference applies that learned capability to the task at hand.",
    life: "It is like a musician performing after rehearsal: every performance takes time and effort, but it does not usually rewrite the skills built through years of training.",
    engineer: "It is like running a previously built container image in a cloud service: the build phase shapes the artifact, while the runtime phase uses the current request to produce a result.",
    misconception: "A common misconception is that the model automatically continues training from every conversation. Most API Inference does not update model weights in real time.",
    safety: "Limit input and output size, timeouts, and retries; record observable usage; and confirm the data-retention policy and service-failure strategy.",
    related: ["fine-tuning", "temperature", "concurrency", "rate-limit"]
  },
  {
    id: "reasoning-model",
    cn: "Reasoning Model",
    en: "Reasoning Model",
    category: "Model Adaptation and Runtime",
    oneLine: "A Reasoning Model is optimized for multistep problem solving and often uses more inference compute to improve performance on complex tasks.",
    professional: "A Reasoning Model is typically trained specifically and performs intermediate computation, search, or self-checking during Inference to handle multistep tasks such as mathematics, coding, and planning. Implementation details vary by model.",
    plain: "It tends to break down and check a complex problem before giving a conclusion, but thinking longer does not guarantee a correct answer.",
    life: "It is like solving a difficult Sudoku by listing candidates, eliminating conflicts, and reviewing steps instead of announcing the first answer that comes to mind.",
    engineer: "It is like planning a database migration, checking dependencies, and validating results before changing the production schema instead of applying the first suggestion immediately.",
    misconception: "A common misconception is that a visible or hidden reasoning process constitutes a mathematical proof. A model can still follow coherent steps to the wrong conclusion.",
    safety: "Set compute budgets, timeouts, and acceptance tests for the task. Decisions involving permissions or real-world impact cannot rely solely on model self-checking.",
    related: ["large-language-model", "inference", "hallucination", "tool-calling"]
  },
  {
    id: "function-calling",
    cn: "Function Calling",
    en: "Function Calling",
    category: "Tools and Integration",
    oneLine: "Function Calling lets a model produce a structured call request that follows a predefined function schema; the application decides whether to execute it.",
    professional: "Function Calling gives the model function names, descriptions, and parameter schemas so it can output an agreed function selection and arguments. The host program validates, authorizes, and executes the request, then returns the result to the model.",
    plain: "The model completes a form with a fixed format; an external program actually accepts the request and performs the work.",
    life: "It is like a customer-service representative completing a flight-change request for a traveler; the airline system must still verify identity, seat availability, and authorization before changing the booking.",
    engineer: "It is like a client constructing a request that conforms to an OpenAPI schema; the server validates fields, identity, and scope before deciding whether to perform the real operation.",
    misconception: "A common misconception is that an operation has happened once the model outputs a function name. It remains only a request until an executor confirms and runs it.",
    safety: "Treat parameters as untrusted input. Use allowlists, least privilege, idempotent design, and approval for high-risk operations; never interpolate them directly into shell commands or SQL.",
    related: ["tool-calling", "api", "system-prompt", "oauth"]
  },
  {
    id: "tool-calling",
    cn: "Tool Calling",
    en: "Tool Calling",
    category: "Tools and Integration",
    oneLine: "Tool Calling lets a model request external capabilities such as search, code execution, or business operations, while execution authority remains with the host system.",
    professional: "Tool Calling is a general mechanism for interaction between a model and external capabilities, including functions, APIs, browsers, files, and command-line tools. The runtime framework exposes capabilities, orchestrates calls, checks permissions, and returns results.",
    plain: "The model can ask to look something up, calculate something, or perform an operation, but an external system must do the actual work and report the result.",
    life: "It is like a project manager sending separate work orders to an electrician, accountant, and courier. The manager chooses a tool, but the work does not happen through words alone.",
    engineer: "It is like an operating system handling a system call: the caller describes an action, and a controlled execution layer checks parameters and permissions before accessing files, processes, or the network.",
    misconception: "A common misconception is that more tools always make an Agent more capable. Wrong selection, excessive permissions, and untrusted results all expand the failure surface.",
    safety: "Minimize the tool set and permissions for each task, limit call count and cost, defend against injection in external results, and require confirmation and auditing for write operations.",
    related: ["function-calling", "api", "system-prompt", "reasoning-model"]
  },
  {
    id: "api",
    cn: "Application Programming Interface",
    en: "Application Programming Interface (API)",
    category: "Interfaces and Security",
    oneLine: "An API is an interface through which software components exchange requests, responses, or events under an explicit contract.",
    professional: "An Application Programming Interface defines available operations, parameters, data formats, authentication, error semantics, and versioning rules, and may be provided through a local library, interprocess communication, or a network protocol.",
    plain: "It specifies how one program asks another program to do something and what format both sides use to communicate.",
    life: "It is like a restaurant ordering window: the menu lists what can be ordered and how to order it, so customers do not need to enter the kitchen and control the stove.",
    engineer: "It is like a REST, gRPC, or message-queue contract: callers interact through a stable interface without depending on the service's internal implementation.",
    misconception: "A common misconception is that API refers only to an internet URL. Operating-system calls, library functions, and device interfaces can also be APIs.",
    safety: "Authenticate, authorize, validate input, and handle timeouts and errors at the boundary. Clients must not store server-side secrets that should not be exposed.",
    related: ["api-key", "oauth", "rate-limit", "function-calling"]
  },
  {
    id: "oauth",
    cn: "OAuth Authorization",
    en: "OAuth 2.0 Authorization Framework",
    category: "Interfaces and Security",
    oneLine: "OAuth lets a user authorize a third-party application to access limited resources without giving that application the account password.",
    professional: "OAuth 2.0 is a delegated-authorization framework: a client obtains an access Token with a specific scope and lifetime through an authorization flow, then accesses a resource server on behalf of the resource owner. Authentication is commonly added through mechanisms such as OpenID Connect.",
    plain: "The user gives an application a pass limited by purpose and time instead of handing over the main account password.",
    life: "It is like a hotel giving a guest a key card that opens only their room and expires at checkout, rather than copying the master key.",
    engineer: "It is like IAM issuing short-lived, restricted credentials: the holder can perform only allowed actions on designated resources, and the server still verifies scope and validity on every request.",
    misconception: "A common misconception is that OAuth itself is a login protocol, or that one authorization grants permanent access to all data. The service controls scope, Token lifetime, and revocation.",
    safety: "Use a recommended authorization flow, exact redirect URIs, and protections such as state and PKCE. Store Tokens securely and request the minimum scope.",
    related: ["api", "api-key", "tool-calling", "system-prompt"]
  },
  {
    id: "api-key",
    cn: "API Key",
    en: "Application Programming Interface Key (API Key)",
    category: "Interfaces and Security",
    oneLine: "An API Key is a secret credential that a service uses to identify and authorize a caller; if exposed, others may misuse its quota and permissions.",
    professional: "An API Key is typically associated with a project, application, or account and validated by the server on each request to authenticate the calling source and apply permissions, quotas, and billing policies. It is commonly used as a bearer credential.",
    plain: "Anyone who obtains this secret can often call the service as that project, so it must not be treated as an ordinary identifier.",
    life: "It is like an office access card: the system recognizes the card and records entry, but someone who finds it may also use it until it is reported lost.",
    engineer: "It is like a shared secret used by a service account: it proves possession of a credential but does not inherently express a particular user's delegated scope as OAuth does.",
    misconception: "A common misconception is that a Key from a subscription product necessarily works with its production API. Credentials for interactive tools, model APIs, and billing entitlements may be separate.",
    safety: "Store it only in secret management or environment variables, never in front-end code, repositories, logs, or chats. Separate it by environment, restrict permissions, and support rotation and revocation.",
    related: ["api", "oauth", "rate-limit", "tool-calling"]
  },
  {
    id: "rate-limit",
    cn: "Rate Limit",
    en: "Rate Limit",
    category: "Interfaces and Security",
    oneLine: "A Rate Limit restricts the number of requests or Tokens allowed within a period to protect capacity and allocate resources fairly.",
    professional: "A Rate Limit may constrain requests, Tokens, or other metrics per second or minute by account, project, model, or endpoint. When the limit is exceeded, the service typically rejects or delays requests and may provide retry information.",
    plain: "Even when quota remains, a request may be temporarily blocked if too many requests arrive in a short time.",
    life: "It is like a freeway ramp meter that releases cars at a controlled pace, not to revoke driving access but to prevent a sudden surge from overwhelming the main road.",
    engineer: "It is like Token-bucket limiting at an API gateway: the current permitted request rate is a different metric from how many concurrent tasks the backend can handle.",
    misconception: "A common misconception is that a Rate Limit is the same as a monthly quota, or that increasing Concurrency always increases throughput. Several independent limits may apply at once.",
    safety: "Clients should honor server retry guidance, use bounded exponential backoff with jitter, and avoid unbounded retries that amplify cost and congestion.",
    related: ["api", "api-key", "concurrency", "token"]
  },
  {
    id: "concurrency",
    cn: "Concurrency",
    en: "Concurrency",
    category: "Engineering Fundamentals",
    oneLine: "Concurrency is the number of tasks in progress during the same period, not the number of tasks completed per second.",
    professional: "Concurrency describes overlapping operation lifetimes and can be implemented with threads, processes, event loops, or distributed requests. Actual throughput also depends on service time, resource contention, and upstream limits.",
    plain: "It asks how many jobs are being handled at once, not how many are ultimately completed in a minute.",
    life: "It is like the number of checkout lanes open at a supermarket. More lanes may reduce queues, but cashier availability and restocking speed can still impose limits.",
    engineer: "It is like the number of in-flight tasks allowed in a work queue: more parallelism can hide waiting time, but lock contention, connection pools, memory, and downstream capacity still set a ceiling.",
    misconception: "A common misconception is that Concurrency and parallelism are identical. Tasks can be interleaved concurrently on one core or truly run in parallel across multiple cores.",
    safety: "Set Concurrency limits, timeouts, and backpressure. For writes, also handle races, idempotency, and ordering requirements.",
    related: ["rate-limit", "inference", "api", "cli"]
  },
  {
    id: "ide",
    cn: "Integrated Development Environment",
    en: "Integrated Development Environment (IDE)",
    category: "Engineering Fundamentals",
    oneLine: "An IDE integrates development capabilities such as code editing, navigation, building, debugging, and version control in one environment.",
    professional: "An Integrated Development Environment combines language services, a project model, debuggers, and build tools to provide semantic completion, diagnostics, refactoring, and execution control for software development.",
    plain: "It is a software-development workbench where you can write code, find definitions, inspect errors, and debug without constantly switching tools.",
    life: "It is like a fully equipped repair station with lighting, diagrams, measuring tools, and test equipment close at hand, while the person responsible still makes the key decisions.",
    engineer: "It is like connecting an editor, version control, testing, deployment, and observability tools to one workbench, while the underlying tools can still run independently.",
    misconception: "A common misconception is that an IDE is a compiler, or that installing one automatically provides the correct toolchain. It often only coordinates external build and debugging components.",
    safety: "Install only trusted extensions and review workspace tasks and auto-run scripts. Use restricted-trust mode when opening an unfamiliar project.",
    related: ["cli", "api", "cdp", "dom"]
  },
  {
    id: "cli",
    cn: "Command-Line Interface",
    en: "Command-Line Interface (CLI)",
    category: "Engineering Fundamentals",
    oneLine: "A CLI is an interface for operating a program through text commands and arguments, well suited to precise reproduction and automation.",
    professional: "A Command-Line Interface receives commands, options, arguments, and standard input from a terminal and reports results through standard output, standard error, and exit codes. Shell scripts and other processes can compose these interfaces.",
    plain: "A user states exactly what the program should do in a line of text, and the program reports the result with text and a status code.",
    life: "It is like ordering from a warehouse counter with fixed codes: the syntax is strict, but the same order is easy to copy, review, and repeat.",
    engineer: "It is like entering list, plan, and apply commands through a cloud platform's CLI; the CLI is an operational interface, not the underlying control-plane implementation.",
    misconception: "A common misconception is that a CLI is inherently more advanced or secure than a graphical interface. It is simply another interaction method, and an incorrect command can be equally destructive.",
    safety: "Before execution, verify the working directory, target, and arguments. Avoid putting secrets on a command line where shell history or process listings may capture them.",
    related: ["ide", "api", "concurrency", "tool-calling"]
  },
  {
    id: "dom",
    cn: "Document Object Model",
    en: "Document Object Model (DOM)",
    category: "Browser Technology",
    oneLine: "The DOM is the object tree into which a browser parses a document so scripts can read and modify it.",
    professional: "The Document Object Model defines document nodes, properties, events, and manipulation interfaces. HTML forms a DOM after parsing, and scripts can continue changing it, so the current DOM may differ from the original source.",
    plain: "After webpage source enters the browser, it becomes an editable tree in which buttons, headings, and forms are nodes.",
    life: "It is like turning a stage script into a physical stage: props can move and actors can be added during the performance, so the current arrangement may differ from the original script.",
    engineer: "It is like parsing source code into a mutable abstract syntax tree: later traversal and transformation operate on the tree instead of repeatedly editing raw characters.",
    misconception: "A common misconception is that viewing page source shows the current DOM, or that the DOM is the same as screen pixels. Styling, layout, and rendering involve additional stages.",
    safety: "When placing untrusted strings in the DOM, use text APIs and safe templates. Avoid injection paths such as innerHTML that can cause cross-site scripting.",
    related: ["cdp", "accessibility-tree", "ide", "api"]
  },
  {
    id: "cdp",
    cn: "Chrome DevTools Protocol",
    en: "Chrome DevTools Protocol (CDP)",
    category: "Browser Technology",
    oneLine: "CDP is a debugging protocol for inspecting and controlling internal capabilities of Chromium browsers.",
    professional: "The Chrome DevTools Protocol exposes browser capabilities for pages, networking, runtime, DOM, performance, and other domains through commands and events. Developer tools and automation clients use them over a debugging connection.",
    plain: "It is like a browser's backstage control channel, allowing tools to inspect network activity, execute scripts, take screenshots, or manipulate pages.",
    life: "It is like a theater's backstage control desk: it monitors each department and issues technical instructions, but these controls are not available to the general audience.",
    engineer: "It is a debugging API for a particular browser implementation: its capabilities are deep and implementation-specific, so another browser cannot be assumed to provide exactly the same events and commands.",
    misconception: "A common misconception is that CDP is a unified web-automation standard for every browser. It primarily targets Chromium, and version and implementation differences must be handled.",
    safety: "A debugging port can read page data and perform privileged operations, so never expose it to an untrusted network. Connecting to a signed-in browser requires explicit authorization.",
    related: ["dom", "accessibility-tree", "cli", "api"]
  },
  {
    id: "accessibility-tree",
    cn: "Accessibility Tree",
    en: "Accessibility Tree",
    category: "Browser Technology",
    oneLine: "The Accessibility Tree is the structure through which a browser presents interface semantics, names, states, and relationships to assistive technologies.",
    professional: "The Accessibility Tree is computed from information including the DOM, ARIA, native control semantics, styles, and visibility state, and is made available to screen readers and other assistive technologies through platform accessibility APIs.",
    plain: "It organizes a webpage's visual interface into a semantic directory of what each item is, what it is called, its current state, and how it can be operated.",
    life: "It is like a museum's tactile and audio guide for blind visitors: it emphasizes the identity of exhibits and navigation relationships rather than reproducing every decorative pixel on the walls.",
    engineer: "It is like a compiler producing a semantic intermediate representation for a specific consumer: purely decorative nodes are omitted, while control roles, labels, and states are normalized.",
    misconception: "A common misconception is that the Accessibility Tree is a complete copy of the DOM. Hidden, decorative, or semantically incomplete nodes may be absent, and incorrect ARIA can distort the result.",
    safety: "Prefer native semantic elements and ensure names, keyboard operation, focus, and state are perceivable. Automated checks do not replace screen-reader testing and user testing.",
    related: ["dom", "cdp", "ide", "multimodal"]
  }
];
